Description of bmech_kinematics
Home > biomechZoo > Toolbox > PiG Ops > bmech_kinematics.m
bmech_kinematics
PURPOSE
BMECH_KINEMATICS(fld,settings) is a batch process function to compute lower-limb
SYNOPSIS
function bmech_kinematics(fld,settings)
DESCRIPTION
 BMECH_KINEMATICS(fld,settings) is a batch process function to compute lower-limb
 joint kinematics according to the plug-in gait (PiG) model
 ARGUMENTS
  fld       ... Folder to batch process (string). Default: folder selection window.
  settings  ... Settings control (struct) with the following fields:
                'graph' (boolean). Graph comparisons agains Vicon. Default, false
                'comp'  (boolean). Vicon vs BiomeZoo RMS diff (if available). Default, true
                'flat' Assume foot flat for static pose. Default: true
 NOTES
 - Static files associated with a given dynamic file should be placed in a
   folder called 'Static' or contain the word 'static' in the file name
   e.g.     root - Subject 1 - cond1
                             - Static
 See also bmech_kinematicsRvdB,bmech_jointcentrePiG, bmech_kinetics
CROSS-REFERENCE INFORMATION
This function calls:
ankleoffsetPiG_data data = ankleoffsetPiG_data(data,sdata) adds the Plantarflexion and Rotation offset
kinematics_data data = KINEMATICS_DATA(data,settings) computes global and lower-limb
makebones_data DATA = MAKEBONES_DATA(data,type,foot_flat,test) creates segment 'bones' for use in kinematic /
This function is called by: