Description of comparePiG
Home > biomechZoo > Toolbox > PiG Ops > comparePiG.m
comparePiG
PURPOSE
COMPAREPIG(data,segment,mO,mA,mL,mP) is used to check outputs of
SYNOPSIS
function comparePiG(data,segment,mO,mA,mL,mP)
DESCRIPTION
 COMPAREPIG(data,segment,mO,mA,mL,mP) is used to check outputs of
 biomechzoo computations against PiG
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
getGlobalCoord [O,A,L,P] = GETGLOBALCOORD(data,O,A,L,P,segment,boneLength,test) moves
makebones DATA = MAKEBONES(data) creates segment 'bones' for use in vicon2groodsuntay or for
makebones_data DATA = MAKEBONES_DATA(data,type,foot_flat,test) creates segment 'bones' for use in kinematic /