Description of getGlobalCoord
Home > biomechZoo > Toolbox > PiG Ops > getGlobalCoord.m
getGlobalCoord
PURPOSE
[O,A,L,P] = GETGLOBALCOORD(data,O,A,L,P,segment,boneLength,test) moves
SYNOPSIS
function [O,A,L,P] = getGlobalCoord(data,O,A,L,P,segment,boneLength,test)
DESCRIPTION
 [O,A,L,P] = GETGLOBALCOORD(data,O,A,L,P,segment,boneLength,test) moves
 locally defined coordinate system vectors to global and scales to bone
 length (required for matching with Vicon outputs)
CROSS-REFERENCE INFORMATION
This function calls:
comparePiG COMPAREPIG(data,segment,mO,mA,mL,mP) is used to check outputs of
This function is called by:
makebones DATA = MAKEBONES(data) creates segment 'bones' for use in vicon2groodsuntay or for
makebones_data DATA = MAKEBONES_DATA(data,type,foot_flat,test) creates segment 'bones' for use in kinematic /