Description of hipjointcentrePiG_data
Home > biomechZoo > Toolbox > PiG Ops > hipjointcentrePiG_data.m
hipjointcentrePiG_data
PURPOSE
data = HIPJOINTCENTREPIG_DATA(data,test) computes left and right hip joint centers for
SYNOPSIS
function [data,localjc] = hipjointcentrePiG_data(data,test)
DESCRIPTION
 data = HIPJOINTCENTREPIG_DATA(data,test) computes left and right hip joint centers for
 plug-in gait (PiG) marker data
 ARGUMENTS
  data      ... Zoo data containing PiG markers. Required markers are 'RASI','LASI','SACR'
                or 'RASI','LASI','RPSI','LPSI'
  test      ... Tests against PiG values, if available (boolean). Default: false
 RETURNS
  data      ... Zoo data with appended hip joint center virtual marker as RHipJC and LHipJC.
  localjc   ... Coordinates of the hip joint centre (struct) in local coordinates
 NOTES
 - computation method based on Davis et al. "A gait analysis data collection and reduction
   technique". Hum Mov Sci. 1991. (see also PiG manual)
 - If zoo files don't contain anthro data (e.g. contain only PiG markers), user must add
   these fields to zoo files in a previous step, or enter antrho values as arguments
 - root mean squared error between the Vicon and custom calculation of the magitude of the
   hip joint centre position stored in the hip joint centre channel event branch
 See also bmech_jointcentrePiG, jointCenterPiG
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
bmech_jointcentrePiG BMECH_JOINTCENTREPIG(fld,joints) is a batch process function to compute left
jointcentrePiG_data data = JOINTCENTREPIG_DATA(data,joint) returns knee, or anke joint centre
makebones_data DATA = MAKEBONES_DATA(data,type,foot_flat,test) creates segment 'bones' for use in kinematic /