Description of kinematics_data
Home > biomechZoo > Toolbox > PiG Ops > kinematics_data.m
kinematics_data
PURPOSE
data = KINEMATICS_DATA(data,settings) computes global and lower-limb
SYNOPSIS
function data = kinematics_data(data,settings)
DESCRIPTION
 data = KINEMATICS_DATA(data,settings) computes global and lower-limb
 joint angles based on the joint coordinate system of Grood and Suntay (1983)
 ARGUMENTS
  data     ...  Zoo data
  settings ...  Settings control (struct) with the following fields:
                'graph' (boolean). Graph comparisons agains Vicon. Default, false
                'comp'  (boolean). Vicon vs BiomeZoo RMS diff (if available). Default, true
 RETURNS
  data    ...   zoo data appended with kinemaitc channels
 NOTES:
 - PiG
   * choice of segment embedded axes for angle computation based on work of
     Vaughan (Dynamics of Human Gait 1999, Appendix B p94-96).
   * Lower limb PiG outputs of this function have been validated
     (see Fig4.ppf and Supplemental Fig2.pdf in ~\biomechZoo-samplestudy\Figures\manuscript\
   * Head angles are not offset by static posture (PiG angles use static offset)
 - OFM
   * choice of segment embedded axes was based on trial and error, comparing
   results to Vicon outputs.
   * Grood and Suntay approach is implemented
 - Belfast Pelvis
   * Belfast pelvis angles based on Baker 'Pelvic angles: a mathematically rigorous
     definition which is consistent with a conventional clinical understanding of
     the terms'. Gait Posture. 2001 Feb;13(1):1-6. doi: 10.1016/s0966-6362(00)00083-7.
 - A correction for vector flips near 90 degrees has been implemented at the knee,
   and BelfastPelvis but might require future updates (see 'checkflip_pyCGM')
 See also makebones_data, bmech_kinematicsPiG, bmech_jointcentrePiG
CROSS-REFERENCE INFORMATION
This function calls:
getDir [data,dir] = GETDIR(data,ch) determines the global axis and direction of
getbones_data [bone,jnt,data] = GETBONES_DATA(data) retrieves bone information from data struct and creates
This function is called by:
bmech_kinematics BMECH_KINEMATICS(fld,settings) is a batch process function to compute lower-limb