Description of makebones_data
Home > biomechZoo > Toolbox > PiG Ops > makebones_data.m
makebones_data
PURPOSE
DATA = MAKEBONES_DATA(data,type,foot_flat,test) creates segment 'bones' for use in kinematic /
SYNOPSIS
function data = makebones_data(data,type,foot_flat,test)
DESCRIPTION
 DATA = MAKEBONES_DATA(data,type,foot_flat,test) creates segment 'bones' for use in kinematic /
 kinetic modelling or for visualization in director. Bones are virtual markers representing
 segment axes.
 ARGUMENTS
  data        ... Zoo data
  type        ... Trial type (String) (static or dynamic)
  foot_flat   ... Foot flat (Boolean) to represent if foot flat should be assumed
                  Default 'false'
  test        ... Test against existing PiG 'bones' (Boolean). Default 'false'
 RETURNS
  data        ... Zoo data with new 'bones' appended
 NOTES
 - Following anthropometric/metainfo data must be available:
   'MarkerDiameter, R/LLegLength,R/LKneeWidth,R/LAnkleWidth
 - Foot length may be inexact during visualization in director. Joint angles are unaffected
 - Only lower-limb bones are currently created
 See also getbones, bmech_kinematics, bmech_kinetics
CROSS-REFERENCE INFORMATION
This function calls:
comparePiG COMPAREPIG(data,segment,mO,mA,mL,mP) is used to check outputs of
getGlobalCoord [O,A,L,P] = GETGLOBALCOORD(data,O,A,L,P,segment,boneLength,test) moves
hipjointcentrePiG_data data = HIPJOINTCENTREPIG_DATA(data,test) computes left and right hip joint centers for
jointcentrePiG_data data = JOINTCENTREPIG_DATA(data,joint) returns knee, or anke joint centre
This function is called by:
bmech_kinematics BMECH_KINEMATICS(fld,settings) is a batch process function to compute lower-limb