Description of forceplate2limbside_data
Home > biomechZoo > Toolbox > Gait > forceplate2limbside_data.m
forceplate2limbside_data
PURPOSE
data = FORCEPLATE2LIMBSIDE_DATA(data,fch,thresh,ref) determines which limb (right
SYNOPSIS
function data = forceplate2limbside_data(data,ch,thresh)
DESCRIPTION
 data = FORCEPLATE2LIMBSIDE_DATA(data,fch,thresh,ref) determines which limb (right
 or left) made contact with force plate n. Information is stored in
 zoosystem (data.zoosystem.Analog.FPlates.LIMBSIDES)
 ARGUMENTS
  data     ...   Zoo data
  ch       ...   name of force plate channels used in algorithm. Default ForceFz
  thresh   ...   Threshold for detecting gait event. Default 20
CROSS-REFERENCE INFORMATION
This function calls:
ZeniEventDetect ind = ZENIEVENTDETECT(data,side,evt,delta) estimates foot strike (FS) and
This function is called by:
bmech_forceplate2limbside BMECH_FORCEPLATE2LIMBSIDE(fld,ch,thresh,ref) determines which limb (right
processGRF_data data = PROCESSGRF_DATA(data,filt,localOr,globalOr,orientFP) prepares force plate data