Description of processGRF_data
Home > biomechZoo > Toolbox > Gait > processGRF_data.m
processGRF_data
PURPOSE
data = PROCESSGRF_DATA(data,filt,localOr,globalOr,orientFP) prepares force plate data
SYNOPSIS
function data = processGRF_data(data,filt,localOr, globalOr,orientFP)
DESCRIPTION
 data = PROCESSGRF_DATA(data,filt,localOr,globalOr,orientFP) prepares force plate data
 for inverse dynamics analysis
 ARGUMENTS
  data       ... Zoo data
  filt       ... Filter settings (struct)
  localOr    ... true local FP origin
  glboalOr   ... FP global origin/orient
  orientFP   ... Orientation of FP wrt global coordinate system
 RETURNS
  data        ...  zoo data with processed GRF quantities
CROSS-REFERENCE INFORMATION
This function calls:
centreofpressure_data data = CENTREOFPRESSURE_DATA(data,localOr,globalOr,thresh) computes COP in global
forceplate2limbside_data data = FORCEPLATE2LIMBSIDE_DATA(data,fch,thresh,ref) determines which limb (right
This function is called by:
bmech_processGRF BMECH_PROCESSGRF(fld,filt) processess raw force plate data in a manner similar