Description of bmech_ml_classification
Home > biomechZoo > Toolbox > Machine Learning > bmech_ml_classification.m
bmech_ml_classification
PURPOSE
BMECH_ML_CLASSIFICATION (data,Model_name) trains a classification model
SYNOPSIS
function Mdl=bmech_ml_classification(data, Model_name)
DESCRIPTION
 BMECH_ML_CLASSIFICATION (data,Model_name) trains a classification model
 ARGUMENTS
 data        ...   struct, struct returned with train_test_split
 Model_name  ...   string,'BDT'     --> Binary Classification Tree
                          'NBayes'  --> Naive bayes
                          'knn'     --> k-Nearest Neighbor Classifier
                          'Bsvm'    --> Binary support vector machines
                          'Blinear' --> Binary Linear Classification
                          'Bkernel' --> Binary Kernel Classification
                          'Msvm'    --> Multiclass support vector machines
 RETURNS
 Mdl         ...   Trained model
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
ml_processing_template_IMU biomechZoo machine learning processing template for IMU data
ml_processing_template_IMU_simple biomechZoo machine learning simple processing template for IMU data
ml_processing_template_mocap biomechZoo machine learning processing template for mocap data