Description of bmech_events2table
Home > biomechZoo > Toolbox > Machine Learning > bmech_events2table.m
bmech_events2table
PURPOSE
BMECH_EVENTS2TABLE extracts local events to tabular form
SYNOPSIS
function table_event = bmech_events2table(fld,ch,event,subjects,Conditions)
DESCRIPTION
 BMECH_EVENTS2TABLE extracts local events to tabular form
 ARGUMENTS
 fld         ...   string, folder to operate on
 ch          ...   string, all channel name.
 event       ...   struct, event.channelName --> all event names to be extracted from that channel.
 subjects    ...   string cell, subject name of all the subjects.
 Conditions  ...   string cell, all Conditions name.
 RETURNS
 table_event ...  Table of events with subjects second last row and conditions last row.
 If event does not exisit it will be 999.
CROSS-REFERENCE INFORMATION
This function calls:
emptytable
This function is called by:
ml_processing_template_IMU biomechZoo machine learning processing template for IMU data
ml_processing_template_mocap biomechZoo machine learning processing template for mocap data