Description of ml_processing_template_IMU_simple
Home > biomechZoo > Toolbox > Machine Learning > ml_processing_template_IMU_simple.m
ml_processing_template_IMU_simple
PURPOSE
biomechZoo machine learning simple processing template for IMU data
SYNOPSIS
This is a script file.
DESCRIPTION
 biomechZoo machine learning simple processing template for IMU data
 This sample script shows how to run a toy binary multiclass support vector
 machines classification model which aims to predict surface type (flat, slope up,
 slope down) based on events (features) extracted from a public gait database
 (see Luo, Coppola, Dixon, et al. A database of human gait performance on irregular
 and uneven surfaces collected by wearable sensors. Sci Data 7, 219 (2020).
 https://doi.org/10.1038/s41597-020-0563-y
 Processed data with features are stored in:
 biomechZoo-help/examples/example data/IMU_4_cycle
 REQUIREMENTS
 - biomechZoo and biomechZoo-help installed
 NOTES:
   - Conditions (y): flat, slope up, slope down
   - Predictors (x): simple statistical features (e.g. Min, Max, mean, std..)
   -Features here are not well designed for classification, see
   ml_processing_template_IMU for better results
CROSS-REFERENCE INFORMATION
This function calls:
bmech_ml_classification BMECH_ML_CLASSIFICATION (data,Model_name) trains a classification model
bmech_zoo2table BMECH_ZOO2TABLE (fld,ch,subjects,Conditions) extracts channel line data
feature_extraction FEATURE_EXTRACTION extracts statistical features from tabular data created by
statsOfMeasure Copyright (c) 2021, Eugenio Bertolini
train_test_split TRAIN_TEST_SPLIT spliting data into train test sets
This function is called by: