Description of ml_processing_template_mocap
Home > biomechZoo > Toolbox > Machine Learning > ml_processing_template_mocap.m
ml_processing_template_mocap
PURPOSE
biomechZoo machine learning processing template for mocap data
SYNOPSIS
This is a script file.
DESCRIPTION
 biomechZoo machine learning processing template for mocap data
 This sample script shows how to run a toy binary KNN classification model which
 aims to predict gait condition (straight vs turning) based on events
 (features) extracted from the biomechzoo sample data, available at
 https://github.com/PhilD001/biomechzoo-help/sample study/Data/zoo files (auto process)*
 * the terminal folder 'zoo files (auto process)' is only available after
 having run the samplestudy_process.m script
 REQUIREMENTS
 - biomechZoo and biomechZoo-help installed
 NOTES:
   Conditions (y): Straight, Turn
   Predictors (x): RightGroundReactionForce_x max','RightHipAngle_y max',
                   'RightAnklePower'max
CROSS-REFERENCE INFORMATION
This function calls:
bmech_events2table BMECH_EVENTS2TABLE extracts local events to tabular form
bmech_ml_classification BMECH_ML_CLASSIFICATION (data,Model_name) trains a classification model
statsOfMeasure Copyright (c) 2021, Eugenio Bertolini
train_test_split TRAIN_TEST_SPLIT spliting data into train test sets
This function is called by: