Description of statsOfMeasure
Home > biomechZoo > Toolbox > Machine Learning > statsOfMeasure.m
statsOfMeasure
PURPOSE
Copyright (c) 2021, Eugenio Bertolini
SYNOPSIS
function [stats] = statsOfMeasure(confusion)
DESCRIPTION
Copyright (c) 2021, Eugenio Bertolini
 All rights reserved.
 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:
 * Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution
 * Neither the name of  nor the names of its
   contributors may be used to endorse or promote products derived from this
   software without specific prior written permission.
 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 The input 'confusion' is the the output of the Matlab function
 'confusionmat'
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
ml_processing_template_IMU biomechZoo machine learning processing template for IMU data
ml_processing_template_IMU_simple biomechZoo machine learning simple processing template for IMU data
ml_processing_template_mocap biomechZoo machine learning processing template for mocap data