Description of normalize_line
Home > biomechZoo > Toolbox > Biomech Ops > normalize_line.m
normalize_line
PURPOSE
[nline,nlength] = NORMALIZE_LINE(r,datalength,method) normalizes data to specific length
SYNOPSIS
function [nr,nlength]=normalize_line(r,datalength,method)
DESCRIPTION
 [nline,nlength] = NORMALIZE_LINE(r,datalength,method) normalizes data to specific length
 ARGUMENTS
  r          ... Matrix data (n x 1 or n x3)
  datalength ... Normalize data to a specific length. Data will have datalength+1 frames.
                 Default: 100 (101 frames)
  method     ... method to interpolate data. Default 'linear'.
                 See interp1 for more options
 RETURNS
  nr         ... Normalized matrix
  nlength    ... New length matrix data
 See also interp1, bmech_normalize, normalize_data
CROSS-REFERENCE INFORMATION
This function calls:
normalize_line [nline,nlength] = NORMALIZE_LINE(r,datalength,method) normalizes data to specific length
This function is called by:
normalize_data data = NORMALIZE_DATA(data,ch,ndatalength,method) performs time normalization
normalize_line [nline,nlength] = NORMALIZE_LINE(r,datalength,method) normalizes data to specific length
resample_data data = resample_data(data,ch,p,q) resampling function without filtering