Description of crop_borders
Home > biomechZoo > Toolbox > Support Functions > export_fig > crop_borders.m
crop_borders
PURPOSE
CROP_BORDERS Crop the borders of an image or stack of images
SYNOPSIS
function [A, vA, vB, bb_rel] = crop_borders(A, bcol, padding, crop_amounts)
DESCRIPTION
CROP_BORDERS Crop the borders of an image or stack of images
   [B, vA, vB, bb_rel] = crop_borders(A, bcol, [padding])
IN:
   A - HxWxCxN stack of images.
   bcol - Cx1 background colour vector.
   padding - scalar indicating how much padding to have in relation to
             the cropped-image-size (0<=padding<=1). Default: 0
   crop_amounts - 4-element vector of crop amounts: [top,right,bottom,left]
             where NaN/Inf indicate auto-cropping, 0 means no cropping,
             and any other value mean cropping in pixel amounts.
OUT:
   B - JxKxCxN cropped stack of images.
   vA     - coordinates in A that contain the cropped image
   vB     - coordinates in B where the cropped version of A is placed
   bb_rel - relative bounding box (used for eps-cropping)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
export_fig EXPORT_FIG Exports figures in a publication-quality format
im2gif IM2GIF Convert a multiframe image to an animated GIF file
print2eps PRINT2EPS Prints figures to eps with improved line styles