Description of fix_lines
Home > biomechZoo > Toolbox > Support Functions > export_fig > fix_lines.m
fix_lines
PURPOSE
FIX_LINES Improves the line style of eps files generated by print
SYNOPSIS
function fstrm = fix_lines(fstrm, fname2)
DESCRIPTION
FIX_LINES  Improves the line style of eps files generated by print
 Examples:
   fix_lines fname
   fix_lines fname fname2
   fstrm_out = fixlines(fstrm_in)
 This function improves the style of lines in eps files generated by
 MATLAB's print function, making them more similar to those seen on
 screen. Grid lines are also changed from a dashed style to a dotted
 style, for greater differentiation from dashed lines.
 The function also places embedded fonts after the postscript header, in
 versions of MATLAB which place the fonts first (R2006b and earlier), in
 order to allow programs such as Ghostscript to find the bounding box
 information.
IN:
   fname - Name or path of source eps file.
   fname2 - Name or path of destination eps file. Default: same as fname.
   fstrm_in - File contents of a MATLAB-generated eps file.
OUT:
   fstrm_out - Contents of the eps file with line styles fixed.
CROSS-REFERENCE INFORMATION
This function calls:
read_write_entire_textfile READ_WRITE_ENTIRE_TEXTFILE Read or write a whole text file to/from memory
using_hg2 USING_HG2 Determine if the HG2 graphics engine is used
This function is called by:
print2eps PRINT2EPS Prints figures to eps with improved line styles