Description of ghostscript
Home > biomechZoo > Toolbox > Support Functions > export_fig > ghostscript.m
ghostscript
PURPOSE
GHOSTSCRIPT Calls a local GhostScript executable with the input command
SYNOPSIS
function varargout = ghostscript(cmd)
DESCRIPTION
GHOSTSCRIPT  Calls a local GhostScript executable with the input command
 Example:
   [status result] = ghostscript(cmd)
 Attempts to locate a ghostscript executable, finally asking the user to
 specify the directory ghostcript was installed into. The resulting path
 is stored for future reference.
 Once found, the executable is called with the input command string.
 This function requires that you have Ghostscript installed on your
 system. You can download this from: http://www.ghostscript.com
 IN:
   cmd - Command string to be passed into ghostscript.
 OUT:
   status - 0 iff command ran without problem.
   result - Output from ghostscript.
CROSS-REFERENCE INFORMATION
This function calls:
user_string USER_STRING Get/set a user specific string
using_hg2 USING_HG2 Determine if the HG2 graphics engine is used
This function is called by:
append_pdfs APPEND_PDFS Appends/concatenates multiple PDF files
eps2pdf EPS2PDF Convert an eps file to pdf format using ghostscript
print2array PRINT2ARRAY Exports a figure to an image array