Description of print2eps
Home > biomechZoo > Toolbox > Support Functions > export_fig > print2eps.m
print2eps
PURPOSE
PRINT2EPS Prints figures to eps with improved line styles
SYNOPSIS
function print2eps(name, fig, export_options, varargin)
DESCRIPTION
PRINT2EPS  Prints figures to eps with improved line styles
 Examples:
   print2eps filename
   print2eps(filename, fig_handle)
   print2eps(filename, fig_handle, export_options)
   print2eps(filename, fig_handle, export_options, print_options)
 This function saves a figure as an eps file, with two improvements over
 MATLAB's print command. First, it improves the line style, making dashed
 lines more like those on screen and giving grid lines a dotted line style.
 Secondly, it substitutes original font names back into the eps file,
 where these have been changed by MATLAB, for up to 11 different fonts.
IN:
   filename - string containing the name (optionally including full or
              relative path) of the file the figure is to be saved as. A
              ".eps" extension is added if not there already. If a path is
              not specified, the figure is saved in the current directory.
   fig_handle - The handle of the figure to be saved. Default: gcf().
   export_options - array or struct of optional scalar values:
       bb_padding - Scalar value of amount of padding to add to border around
                    the cropped image, in points (if >1) or percent (if <1).
                    Can be negative as well as positive; Default: 0
       crop       - Cropping flag. Deafult: 0
       fontswap   - Whether to swap non-default fonts in figure. Default: true
       font_space - Character used to separate font-name terms in the EPS output
                    e.g. "Courier New" => "Courier-New". Default: ''
                    (available only via the struct alternative)
       renderer   - Renderer used to generate bounding-box. Default: 'opengl'
                    (available only via the struct alternative)
       crop_amounts - 4-element vector of crop amounts: [top,right,bottom,left]
                    (available only via the struct alternative)
   print_options - Additional parameter strings to be passed to the print command
CROSS-REFERENCE INFORMATION
This function calls:
crop_borders CROP_BORDERS Crop the borders of an image or stack of images
fix_lines FIX_LINES Improves the line style of eps files generated by print
print2array PRINT2ARRAY Exports a figure to an image array
read_write_entire_textfile READ_WRITE_ENTIRE_TEXTFILE Read or write a whole text file to/from memory
using_hg2 USING_HG2 Determine if the HG2 graphics engine is used
This function is called by:
export_fig EXPORT_FIG Exports figures in a publication-quality format
print2array PRINT2ARRAY Exports a figure to an image array