Description of print2array
Home > biomechZoo > Toolbox > Support Functions > export_fig > print2array.m
print2array
PURPOSE
PRINT2ARRAY Exports a figure to an image array
SYNOPSIS
function [A, bcol] = print2array(fig, res, renderer, gs_options)
DESCRIPTION
PRINT2ARRAY  Exports a figure to an image array
 Examples:
   A = print2array
   A = print2array(figure_handle)
   A = print2array(figure_handle, resolution)
   A = print2array(figure_handle, resolution, renderer)
   A = print2array(figure_handle, resolution, renderer, gs_options)
   [A bcol] = print2array(...)
 This function outputs a bitmap image of the given figure, at the desired
 resolution.
 If renderer is '-painters' then ghostcript needs to be installed. This
 can be downloaded from: http://www.ghostscript.com
 IN:
   figure_handle - The handle of the figure to be exported. Default: gcf.
   resolution - Resolution of the output, as a factor of screen
                resolution. Default: 1.
   renderer - string containing the renderer paramater to be passed to
              print. Default: '-opengl'.
   gs_options - optional ghostscript options (e.g.: '-dNoOutputFonts'). If
                multiple options are needed, enclose in call array: {'-a','-b'}
 OUT:
   A - MxNx3 uint8 image of the figure.
   bcol - 1x3 uint8 vector of the background color
CROSS-REFERENCE INFORMATION
This function calls:
ghostscript GHOSTSCRIPT Calls a local GhostScript executable with the input command
print2eps PRINT2EPS Prints figures to eps with improved line styles
user_string USER_STRING Get/set a user specific string
using_hg2 USING_HG2 Determine if the HG2 graphics engine is used
This function is called by:
export_fig EXPORT_FIG Exports figures in a publication-quality format
print2eps PRINT2EPS Prints figures to eps with improved line styles