Description of user_string
Home > biomechZoo > Toolbox > Support Functions > export_fig > user_string.m
user_string
PURPOSE
USER_STRING Get/set a user specific string
SYNOPSIS
function string = user_string(string_name, string)
DESCRIPTION
USER_STRING  Get/set a user specific string
 Examples:
   string  = user_string(string_name)
   isSaved = user_string(string_name, new_string)
 Function to get and set a string in a system or user specific file. This
 enables, for example, system specific paths to binaries to be saved.
 The specified string will be saved in a file named <string_name>.txt,
 either in a subfolder named .ignore under this file's folder, or in the
 user's prefdir folder (in case this file's folder is non-writable).
 IN:
   string_name - String containing the name of the string required, which
                 sets the filename storing the string: <string_name>.txt
   new_string  - The new string to be saved in the <string_name>.txt file
 OUT:
   string  - The currently saved string. Default: ''
   isSaved - Boolean indicating whether the save was succesful
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
eps2pdf EPS2PDF Convert an eps file to pdf format using ghostscript
ghostscript GHOSTSCRIPT Calls a local GhostScript executable with the input command
pdftops PDFTOPS Calls a local pdftops executable with the input command
print2array PRINT2ARRAY Exports a figure to an image array