Description of angular_kin
Home > biomechZoo > Toolbox > PiG Ops > IDA Ops > IDA support functions > angular_kin.m
angular_kin
PURPOSE
ANGULAR_KIN returns angular kinematic quantities required for inverse dynamics
SYNOPSIS
function AKIN = angular_kin(LKIN,fsamp,f)
DESCRIPTION
 ANGULAR_KIN returns angular kinematic quantities required for inverse dynamics
 ARGUMENTS
 LKIN    ...  linear kinematics
 fsamp   ...  sampling rate of signal
 f       ...  choice of filtering 0 = no, 1 = yes (with default) or f =
                struct with filter properties (see bmech filter)
 RETURNS
 AKIN  ...   structured array containing grood
             and suntay axes, euler axes, segment angular velocity and
             accelerations. ALL IN LOCAL
  Created May 2008 by Phil Dixon
 updated January 2011
 - channel names in variable KIN were changed by vicon2groodsuntay.
   Changes are reflected here.
 - future update required to account for oxford model
 Updated February 2011
 - Joint kinematics are not needed for any IDA calculations. Removed input
 KIN from function and joint kinematics are not included in AKIN
 Updated August 2013
 - user has control over choice of filtering
CROSS-REFERENCE INFORMATION
This function calls:
ang_acc ANG_ACC calculates angular acc of segments
ang_velocity ANG_VELOCITY calculates angular velocity of segments
euler EULER creates euler transformations.
This function is called by:
zoo2ida zoo2IDA will output segment information from zoo data created by JJ.