Description of dynamics
Home > biomechZoo > Toolbox > PiG Ops > IDA Ops > IDA support functions > dynamics.m
dynamics
PURPOSE
1) LOAD ANALOG DATA
SYNOPSIS
function [DYNAMICS,Tz] = dynamics(ANTHRO,LKIN,COM,AKIN,COP,Tz,data,g,mass)
DESCRIPTION
   1) LOAD ANALOG DATA
   load downsampled & filtered analog data from zoo2ida
CROSS-REFERENCE INFORMATION
This function calls:
F_segment F_SEGMENT returns the proximal force at the joint
M_foot M_ANKLE determines the moment at the ankle
M_segment M_ANKLE determines the moment at the ankle
P_segment ARGUMENTS
g value of acceleration in different cities. You can get really nerdy and
This function is called by: