Description of rate_of_change_momentum
Home > biomechZoo > Toolbox > PiG Ops > IDA Ops > IDA support functions > rate_of_change_momentum.m
rate_of_change_momentum
PURPOSE
RATE_OF_CHANGE_MOMENTUM returns the rate of change of the angular
SYNOPSIS
function Ldot = rate_of_change_momentum (I, omega, alpha)
DESCRIPTION
   RATE_OF_CHANGE_MOMENTUM returns the rate of change of the angular
   momentum (L)
   ARGUMENTS:
   I     ...  moment of inertia matrix calculated in ANTHRO
              [ I_x   I_y   I_z]
   omega ...  angular velocity matrix calculated in ANG_VELOCITY
   alpha ...   angular acceleration matrix calculated in ANG_ACC
   RETURNS
   Ldot ...  rate of change of angular momentum
 Notes: see Vaughan1999 appendix B p99
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
M_foot M_ANKLE determines the moment at the ankle
M_foot_hf M_ANKLE determines the moment at the ankle
M_lshank M_ANKLE determines the moment at the ankle
M_lthigh M_ANKLE determines the moment at the ankle
M_rshank M_ANKLE determines the moment at the ankle
M_rthigh M_ANKLE determines the moment at the ankle
M_segment M_ANKLE determines the moment at the ankle
M_segment_2 M_ANKLE determines the moment at the ankle
M_segment_hf M_ANKLE determines the moment at the ankle
M_segment_old M_ANKLE determines the moment at the ankle