Description of zoo2ida
Home > biomechZoo > Toolbox > PiG Ops > IDA Ops > IDA support functions > zoo2ida.m
zoo2ida
PURPOSE
zoo2IDA will output segment information from zoo data created by JJ.
SYNOPSIS
function [ANTHRO,LKIN,COM, AKIN,DYNAMICS,COP,Tz,FPproperties,StrideProperties,StridePropertiesCOP,HS0,HS3,TO0,data] = zoo2ida(zdata,cdata,zfilename)
DESCRIPTION
   zoo2IDA will output segment information from zoo data created by JJ.
   PREREQUISITES
   zdata must contain the events TO and HS in the channels fz1 and fz2
   ARGUMENTS
   ZDATA        ...   loaded .zoo file
   CDATA        ...   loaded coordinate data from xls file in matrix form
   ZFILENAME    ...   full path of file as string
   RETURNS
   DYNAMICS     ...   Struct containing force,moment and power info
   AKIN         ...   struct containing all joint angles
   Tz
   FProperties  ...   struct containing REFdis, REFort, dis
                         -REFdis(3 element vector that defines the origin of the data)
                         -REFort(3X3 matrix of ijk unit vectors that defines the coordinate system of the zoo data
                         -dis (distance between force plates)
   HS3      ... Heel strike 3 calculated from ida bones
   TO0      ... Toe off 0 calculated from ida bones
   Caution.  all segments above and including the pelvis do not have the
   proper center of mass
   Created by JJ Loh  2007/06/21
   Departement of Kinesiology
   McGill University, Montreal, Quebec Canada
   Updated by JJ LOH 2007/07/05
   1)output xyz vectors for inverse dynamic analysis
   2)redefined the origin as REFdis
   3)redefined the orientation as REFort
   Updatad by Phil Dixon 2007/07/07
   1)output moments
   2)COM based on DeLeva (adjusted Zatsiorsky)
   3)added thorax orientation axes as output
   4) output bone info is in meters
   Updated by JJ & Phil 2007/09/12
   Added heel strike 3
   Updated by Phil 2007/09/23
   added TO0
   updated by Phil 2007/11/15
    -COP calculation takes true centre of plate into consideration
    -Free torque calculation corrected (as per kwon3d)
  updated 2007/12/10
  -Tz converted to action oriented system
 updated 2007/12/16
 -fixed dis (distance between plates)
 -can now accept and process kinematics of t-pose data. Analog channels
 contain garbage
  NOTES:
    -data in "data" is scaled down by a factor of 1000. Multiply by 1000
    to fit onto director graphs
CROSS-REFERENCE INFORMATION
This function calls:
COP_oneplate COP_ONEPLATE calculats COP of 2 force plates placed a distance dis apart
F_lfoot F_FOOT returns the proximal force at ankle
F_lsegment F_FOOT returns the proximal force at ankle
F_rfoot F_FOOT returns the proximal force at ankle
F_rsegment F_FOOT returns the proximal force at ankle
M_lshank M_ANKLE determines the moment at the ankle
M_lthigh M_ANKLE determines the moment at the ankle
M_rshank M_ANKLE determines the moment at the ankle
M_rthigh M_ANKLE determines the moment at the ankle
angular_kin ANGULAR_KIN returns angular kinematic quantities required for inverse dynamics
anthro ANTHRO returns anthropometric quantities
fplate_coord FLATE_COORD creates local coordinate system at plate 1 for both
free_torque FREE_TORQUE calculates the free torque about the z-axis
g value of acceleration in different cities. You can get really nerdy and
getdata NOTES
linear_kin LINEAR_KIN returns kinematic quantities required for inverse dynamics
This function is called by: