Description of finddobj
Home > biomechZoo > Toolbox > Visualization > director support functions > finddobj.m
finddobj
PURPOSE
varargout = FINDDOBJ(action,varargin) is a function for short hand
SYNOPSIS
function varargout = finddobj(action,varargin)
DESCRIPTION
 varargout =  FINDDOBJ(action,varargin) is a function for short hand
 finding of obejcts in director
CROSS-REFERENCE INFORMATION
This function calls:
finddobj varargout = FINDDOBJ(action,varargin) is a function for short hand
This function is called by:
finddobj varargout = FINDDOBJ(action,varargin) is a function for short hand
loadbones
mark MARK(action,varargin) is an director function
marker varargout = marker(action,varargin) performs various actions for director
props varargout = PROPS(action,varargin) creates various props used by director
propsBones