Description of mark
Home > biomechZoo > Toolbox > Visualization > director support functions > mark.m
mark
PURPOSE
MARK(action,varargin) is an director function
SYNOPSIS
function mark(action,varargin)
DESCRIPTION
 MARK(action,varargin) is an director function
CROSS-REFERENCE INFORMATION
This function calls:
finddobj varargout = FINDDOBJ(action,varargin) is a function for short hand
marker varargout = marker(action,varargin) performs various actions for director
props varargout = PROPS(action,varargin) creates various props used by director
This function is called by:
marker varargout = marker(action,varargin) performs various actions for director
props varargout = PROPS(action,varargin) creates various props used by director