Description of props
Home > biomechZoo > Toolbox > Visualization > director support functions > props.m
props
PURPOSE
varargout = PROPS(action,varargin) creates various props used by director
SYNOPSIS
function varargout = props(action,varargin)
DESCRIPTION
 varargout = PROPS(action,varargin) creates various props used by director
 Updated by JJ Loh and Philippe C. Dixon June 2015
 - new case added to load the skate props
 Updated by Philippe C. Dixon November 2015
 - props relies on exisitng functions to prepare COP data
 - all available bones will plot
 - force plate props will be resized based on corners data
   (data.zoosystem.Analog.FPlates.CORNERS), if available
CROSS-REFERENCE INFORMATION
This function calls:
clean
finddobj varargout = FINDDOBJ(action,varargin) is a function for short hand
mark MARK(action,varargin) is an director function
marker varargout = marker(action,varargin) performs various actions for director
props varargout = PROPS(action,varargin) creates various props used by director
This function is called by:
mark MARK(action,varargin) is an director function
marker varargout = marker(action,varargin) performs various actions for director
props varargout = PROPS(action,varargin) creates various props used by director