Description of uitree_director
Home > biomechZoo > Toolbox > Visualization > director support functions > uitree_director.m
uitree_director
PURPOSE
UITREE_DIRECTOR controls the display of the tree representation of loaded
SYNOPSIS
function uitree_director(hnd,data)
DESCRIPTION
 UITREE_DIRECTOR controls the display of the tree representation of loaded
 data in director
 ARGUMENTS
  hnd    ...  handle to director figure or tab
  data   ...  loaded zoo file
CROSS-REFERENCE INFORMATION
This function calls:
clean
display_director_graph
marker varargout = marker(action,varargin) performs various actions for director
This function is called by: