% csv2zooVicon_example demonstrates how to convert a csv file exported from the 
% Vicon motion capture system to zoo format using the csv2zooVicon function
%
% Usage: Some vicon users export their data to csv format. The structure of these files
% is consistent, but cannot be easily read by csvread due to mix of strings and double data. 
% csv2zooVicon allows these users to convert their files for use with biomechZoo
%
% Example: The files in our example data folder (~/examples/example data) contain 
% '.csv' file generated by Vicon Nexus. Note the Legacy - ?Export data to
% ASCII file" setting was used to generate this file


% Example setup
%
clc
close all
clear variables

time = 2; 
fld = example_setup;
pause(time)



% get file
%
% 
ext = '.csv';
disp(['In this folder, we have a ',ext,' file:'])
fl = engine('path',fld,'extension',ext,'search file','529_1_g_01');

batchdisp(fl{1},' ')
disp(' ')
pause(time)

% Process set up
%
del = false;
disp('We call ''csv2zooVicon(fld,del)'', where: ')
disp(['del = ', num2str(del)])
disp(' ')
pause(time)

data = csv2zooVicon(fl,del);
    
     
% Final message to user
%
[~,file] = fileparts(data.zoosystem.SourceFile);
disp(' ')
disp(['We load the zoo file created from ',file,ext])
disp(' ')
disp('Explore the new zoo file created')
disp(' ')
clear fl fld chHeaderRow del time ext file
