Description of addchannel_data
Home > biomechZoo > Toolbox > Zoo Processing > addchannel_data.m
addchannel_data
PURPOSE
data = ADDCHANNEL_DATA(data,ch,ndata,section)
SYNOPSIS
function data = addchannel_data(data,ch,ndata,section)
DESCRIPTION
 data = ADDCHANNEL_DATA(data,ch,ndata,section)
 ARGUMENTS
  data     ...  Zoo data (struct)
  ch       ...  Name of new channel to add (string)
  ndata    ...  vector of new data to be added to new channel
  section  ...  'Video' or 'Analog' section
 RETURNS
  data    ...   Zoo data with new channel appended
 NOTES
 - unlike 'bmech_removechannel', there is no batch processing equivalent
   function to add channels since for a given channel, each file needs to contain
   specific data.
 See also bmech_removechannel, bmech_removeevent, bmech_addevent, removechannel_data
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
combine_data data = COMBINE_DATA(data1,data2,method)
explode_data data = EXPLODE_DATA(data,ch) explodes channels
explodechannel_data data = EXPLODECHANNEL_DATA(data,ch) explodes channels
mergechannel_data data = MERGECHANNEL_DATA(data,ch) explodes channels
renamechannel_data data = RENAMECHANNEL_DATA(data,och,nch) renames zoo channels