Description of explode_data
Home > biomechZoo > Toolbox > Zoo Processing > explode_data.m
explode_data
PURPOSE
data = EXPLODE_DATA(data,ch) explodes channels
SYNOPSIS
function data = explode_data(data,ch)
DESCRIPTION
 data = EXPLODE_DATA(data,ch) explodes channels
 ARGUMENTS
  data     ... Zoo file
  ch       ...  Channels to explode (single string or cell array of strings).
                Default: explode all channels 'all'
 NOTES
 - existing events are transferred to the '_x' dimension
 - Appropriate section (video or analog) determined automatically
 See also bmech_explode
CROSS-REFERENCE INFORMATION
This function calls:
addchannel_data data = ADDCHANNEL_DATA(data,ch,ndata,section)
removechannel_data data= REMOVECHANNEL_DATA(data,ch) removes channels from zoo files
This function is called by:
bmech_explode BMECH_EXPLODE(fld,ch) batch process split of n x 3 channel data into three n x 1
bmech_reptrial BMECH_REPTRIAL(fld,chrp) finds a representative trial per subject/condition based