Description of mergechannel_data
Home > biomechZoo > Toolbox > Zoo Processing > mergechannel_data.m
mergechannel_data
PURPOSE
data = MERGECHANNEL_DATA(data,ch) explodes channels
SYNOPSIS
function data = mergechannel_data(data,ch)
DESCRIPTION
 data = MERGECHANNEL_DATA(data,ch) explodes channels
 ARGUMENTS
  data     ...  Zoo file
  ch       ...  Channel(s) to operate on (cell array of 3 strings)
CROSS-REFERENCE INFORMATION
This function calls:
addchannel_data data = ADDCHANNEL_DATA(data,ch,ndata,section)
removechannel_data data= REMOVECHANNEL_DATA(data,ch) removes channels from zoo files
This function is called by:
bmech_merge BMECH_MERGE(fld,ch) batch process merging of exploded channels