Description of removechannel_data
Home > biomechZoo > Toolbox > Zoo Processing > removechannel_data.m
removechannel_data
PURPOSE
data= REMOVECHANNEL_DATA(data,ch) removes channels from zoo files
SYNOPSIS
function data= removechannel_data(data,ch)
DESCRIPTION
 data= REMOVECHANNEL_DATA(data,ch) removes channels from zoo files
 ARGUMENTS
  data     ...  Zoo data (struct)
  ch       ...  Channels to remove (string or cell array of strings)
 RETURNS
  data     ...  Zoo data with ch removed from struct
 See also bmech_removechannel, bmech_removeevent, bmech_addevent, bmech_removeevent
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
bmech_removechannel BMECH_REMOVECHANNEL(fld,ch,action) batch process removal of unwanted channels
bmech_reptrial BMECH_REPTRIAL(fld,chrp) finds a representative trial per subject/condition based
explode_data data = EXPLODE_DATA(data,ch) explodes channels
explodechannel_data data = EXPLODECHANNEL_DATA(data,ch) explodes channels
mergechannel_data data = MERGECHANNEL_DATA(data,ch) explodes channels
renamechannel_data data = RENAMECHANNEL_DATA(data,och,nch) renames zoo channels