Description of renamechannel_data
Home > biomechZoo > Toolbox > Zoo Processing > renamechannel_data.m
renamechannel_data
PURPOSE
data = RENAMECHANNEL_DATA(data,och,nch) renames zoo channels
SYNOPSIS
function data = renamechannel_data(data,och,nch)
DESCRIPTION
 data = RENAMECHANNEL_DATA(data,och,nch) renames zoo channels
 ARGUMENTS
  data  ...  zoo file
  och   ...  Name of old channels (cell array of strings or single string) e.g. {'ch1','ch2'}
  nch   ...  Name of new channels (cell array of strings or single string)
 RETURNS
  data  ...  Zoo files with new channels appended
 See also bmech_renamechannel, removechannel_data, addchannel_data
CROSS-REFERENCE INFORMATION
This function calls:
addchannel_data data = ADDCHANNEL_DATA(data,ch,ndata,section)
removechannel_data data= REMOVECHANNEL_DATA(data,ch) removes channels from zoo files
This function is called by:
bmech_renamechannel BMECH_RENAMECHANNEL(fld,och,nch) batch process renaming of channels