Description of buttondown
Home > biomechZoo > Toolbox > Visualization > ensembler support functions > buttondown.m
buttondown
PURPOSE
BUTTONDOWN(settings) controls behavior of button clicks in ensembler
SYNOPSIS
function buttondown(settings)
DESCRIPTION
 BUTTONDOWN(settings) controls behavior of button clicks in ensembler
CROSS-REFERENCE INFORMATION
This function calls:
concatPrompt prmt = CONCATENSPROMPT(prmt,n) recursively concatenates the prompt at the top of ensembler
ensembler_axis_highlight curAx = ENSEMBLER_AXIS_HIGHLIGHT(bool) sets the color of current axis to red, all
findensobj hnd = FINDENSOBJ(action,varargin) searches for objects in ensembler using
This function is called by: