Description of concatPrompt
Home > biomechZoo > Toolbox > Visualization > ensembler support functions > concatPrompt.m
concatPrompt
PURPOSE
prmt = CONCATENSPROMPT(prmt,n) recursively concatenates the prompt at the top of ensembler
SYNOPSIS
function prmt = concatPrompt(prmt,n)
DESCRIPTION
 prmt = CONCATENSPROMPT(prmt,n) recursively concatenates the prompt at the top of ensembler
 figures to a maximum number n of characters
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
buttondown BUTTONDOWN(settings) controls behavior of button clicks in ensembler
ensembler_msgbox ENSEMBLER_MSGBOX(fld,msg) creates message box at bottom of figure
ensembler_prompt SHOW_ENSEMBLER_PROMPT(fld,action)