Description of createlines
Home > biomechZoo > Toolbox > Visualization > ensembler support functions > createlines.m
createlines
PURPOSE
stop_load = CREATELINES(fig,data,fl,settings) used by ensembler GUI to
SYNOPSIS
function stop_load = createlines(fig,data,fl,settings)
DESCRIPTION
 stop_load = CREATELINES(fig,data,fl,settings) used by ensembler GUI to
 plot lines in each axis
CROSS-REFERENCE INFORMATION
This function calls:
ensembler_msgbox ENSEMBLER_MSGBOX(fld,msg) creates message box at bottom of figure
ensembler_settings settings = ENSEMBLER_SETTINGS(user_settings) sets all the default style settings for ensembler
This function is called by:
loaddata LOADDATA(fld,figs,settings) loads line and event data into ensembler
loadfile
updatefile