Description of ensemble_figsize
Home > biomechZoo > Toolbox > Visualization > ensembler support functions > ensemble_figsize.m
ensemble_figsize
PURPOSE
figures out good ensembler size based on nmber of rows and columns
SYNOPSIS
function [f_width,f_height,xwid,ywid,msgbox_space,msg] = ensemble_figsize(nrows,ncols,xwid,ywid,units)
DESCRIPTION
 figures out good ensembler size based on nmber of rows and columns
 and width of each axis
CROSS-REFERENCE INFORMATION
This function calls:
ensemble_figsize figures out good ensembler size based on nmber of rows and columns
This function is called by:
ensemble_figsize figures out good ensembler size based on nmber of rows and columns
start_ensembler START_ENSEMBLER is a stand-alone function to control startup window of