Description of ensembler_msgbox
Home > biomechZoo > Toolbox > Visualization > ensembler support functions > ensembler_msgbox.m
ensembler_msgbox
PURPOSE
ENSEMBLER_MSGBOX(fld,msg) creates message box at bottom of figure
SYNOPSIS
function ensembler_msgbox(fld,msg)
DESCRIPTION
 ENSEMBLER_MSGBOX(fld,msg) creates message box at bottom of figure
CROSS-REFERENCE INFORMATION
This function calls:
concatPrompt prmt = CONCATENSPROMPT(prmt,n) recursively concatenates the prompt at the top of ensembler
This function is called by:
addotherchannelevent ADDOTHERCHANNELEVENT(fld) loads events from another channel into the
createlines stop_load = CREATELINES(fig,data,fl,settings) used by ensembler GUI to
ensembler_eventval ENSEMBLER_EVENTVAL(fld) prepares data for export to a spreadsheet using eventval
ensembler_processing ENSEMBLER_PROCESSING(fld,action) saves, loads, and runs processing
keypress_ensembler keypress_ensembler is a stand-alone suppot function for ensembler
loaddata LOADDATA(fld,figs,settings) loads line and event data into ensembler
reorder_bars
startup_ensembler STARTUP_ENSEMBLER initializes the GUI labels
stdpatch_ensembler