Description of findfigure
Home > biomechZoo > Toolbox > Visualization > ensembler support functions > findfigure.m
findfigure
PURPOSE
SYNOPSIS
function r = findfigure(fl,fig)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
isgoodfile indx = strfind(nm,'/');
This function is called by:
loaddata LOADDATA(fld,figs,settings) loads line and event data into ensembler
loadfile