Description of findensobj
Home > biomechZoo > Toolbox > Visualization > ensembler support functions > findensobj.m
findensobj
PURPOSE
hnd = FINDENSOBJ(action,varargin) searches for objects in ensembler using
SYNOPSIS
function hnd = findensobj(action,varargin)
DESCRIPTION
 hnd = FINDENSOBJ(action,varargin) searches for objects in ensembler using
 special properties
CROSS-REFERENCE INFORMATION
This function calls:
findensobj hnd = FINDENSOBJ(action,varargin) searches for objects in ensembler using
This function is called by:
buttondown BUTTONDOWN(settings) controls behavior of button clicks in ensembler
clear999
combine
combine_all
combine_custom
combine_within combine_within used to combine different axes with full freedom. Great for comparing
ensembledata ENSEMBLEDATA (vartype,settings) summarizes line and event data from ensembler
ensembledatabysubject
findensobj hnd = FINDENSOBJ(action,varargin) searches for objects in ensembler using
keypress_ensembler keypress_ensembler is a stand-alone suppot function for ensembler
setaxes