Description of resize_ensembler
Home > biomechZoo > Toolbox > Visualization > ensembler support functions > resize_ensembler.m
resize_ensembler
PURPOSE
RESIZE_ENSEMBLER(AX) automaticall resizes bar and line graph axes in ensembler figures
SYNOPSIS
function resize_ensembler(ax)
DESCRIPTION
 RESIZE_ENSEMBLER(AX) automaticall resizes bar and line graph axes in ensembler figures
 ARGUMENTS
  ax  ...   axis handle. Used for bar graphs. Default none
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
continuousstats CONTINUOUSSTATS is a standalong function to perform Bootstrap analysis
coupling_angles COUPLING_ANGLES is a standalone function for ensembler
makebar MAKEBAR creates bar graphs from ensembler figures