Description of startup_ensembler
Home > biomechZoo > Toolbox > Visualization > ensembler support functions > startup_ensembler.m
startup_ensembler
PURPOSE
STARTUP_ENSEMBLER initializes the GUI labels
SYNOPSIS
function startup_ensembler(nm,nrows,ncols,xwid,ywid,xspace,yspace,fw,fh,i,nfigs,FontName,FontSize,units,msgbox_space,opening_msg)
DESCRIPTION
 STARTUP_ENSEMBLER initializes the GUI labels
CROSS-REFERENCE INFORMATION
This function calls:
ensembler_msgbox ENSEMBLER_MSGBOX(fld,msg) creates message box at bottom of figure
getspacing
This function is called by:
blanknorm
start_ensembler START_ENSEMBLER is a stand-alone function to control startup window of