Description of start_ensembler
Home > biomechZoo > Toolbox > Visualization > ensembler support functions > start_ensembler.m
start_ensembler
PURPOSE
START_ENSEMBLER is a stand-alone function to control startup window of
SYNOPSIS
function start_ensembler
DESCRIPTION
 START_ENSEMBLER is a stand-alone function to control startup window of
 options for ensembler GUI
CROSS-REFERENCE INFORMATION
This function calls:
ensemble_figsize figures out good ensembler size based on nmber of rows and columns
partitionname
startup_ensembler STARTUP_ENSEMBLER initializes the GUI labels
This function is called by: