Description of ensembler
Home > biomechZoo > Toolbox > Visualization > ensembler.m
ensembler
PURPOSE
SYNOPSIS
function ensembler(action)
DESCRIPTION
 ENSEMBLER is the main graphical user interface (GUI) for the zoosystem
 Time-series data can be graphed by group/channel.
 QUICK GUIDE
 - The user can change groupings by entering appropriate fields in the 'name'
   section of the dialog box. These names should correspond to folder names
   in the user's databa
 - Individual axes must be tagged to list a given channel before accepting line data
 EXAMPLES
   e.g.1 There are two groups: 'elite' and 'rec' performing a task. Typing 'elite rec'
   in the 'name' section at startup will create two windows allowing the user to graph
   all files in 'elite' folder together and all files in 'rec' together. A space must
   separate input strings.
   e.g.2 There are two groups 'elite' and 'rec' performing two conditions
   'slap' and 'wrist' (ice hockey shot styles). Typing 'elite+slap elite+wrist rec+slap rec+wrist'
   will create 4 windows. Each window will collect all files containing both input strings.
 NOTES
 - Ensembler can also ensemble event data. Ensembled events may not "sit" on the mean
   line due to standard deviation of their respective indices, i.e. different trials may
   have different index for a common event
 - There are known functionality issues graphing patches (e.g. standard deviation cloud)
   on Mac OSX platforms
 - There are known functionality issues with errorbars on Matlab version 2014a and up
 - Functions tested on v2012a on MAC OS 10.8.6 and Windows 7
 - Users wishing to use the exact version described in the biomechZoo
   manuscript can download the original code on github
CROSS-REFERENCE INFORMATION
This function calls:
ensembler
sigdiff SIGDIFF(x,y,FontName,FontSize) displays a beautiful significant difference 'star'
This function is called by:
ensembler