Description of actor
Home > biomechZoo > Toolbox > Support Functions > actor.m
actor
PURPOSE
SYNOPSIS
function varargout = actor(action,varargin)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
accessoryfxn
actor
cameraman
colorpallete
costume
ctransform vout = CTRANSFORM(c1,c2,vec) will transform a vector from c1 to c2 (T2/1)
currentobject
currentperson Updated Sept 2016
euler2unit
extension varargout = extension(f,ext) returns file extension. File extension can be changed if
findfield [r,chn] = FINDFIELD(st,evt) searches through all subbranches in a structured array
findpart
grips edited by Phil Dixon Dec 2010
point2line this function returns the row index of the matrix of points (pt) closest
specialobject Updated by Philippe C. Dixon March 30th 2016
uigetstruct
unit2euler
vecrotate vout = VECROTATE(vin,ang,ax) rotates a vector any number of degrees about any axis
This function is called by:
actor
bargraphfxn
costume
directorold updated by Phil Dixon Oct 2009
directorold2 updated by Phil Dixon Oct 2009
grips edited by Phil Dixon Dec 2010
openall standalone function used by director
uicreatebars