Description of angle
Home > biomechZoo > Toolbox > Support Functions > angle.m
angle
PURPOSE
Calculates the smallest angle between two vectors, m1 and m2.
SYNOPSIS
function r = angle(m1,m2,ref)
DESCRIPTION
Calculates the smallest angle between two vectors, m1 and m2.
 r = angle(m1,m2,ref)
 ARGUMENTS
  m1    ...      1st nx3 vector
  m2    ...      2nd nx3 vector
  ref   ...      string: 'deg' for degrees or 'rad' for radians.
                 Default is degrees.
 OUTPUTS
  r    ...       angle
 Created by JJ Loh 2006
 updated by Phil Dixon Oct 2008
CROSS-REFERENCE INFORMATION
This function calls:
makerow MAKEROW forces a column vector to be a row vector
This function is called by:
cameraman
cine_groot_suntay
fan
propscopy
rotatefaces
specialobject Updated by Philippe C. Dixon March 30th 2016
teximage TEXIMAGE display a LaTeX string as a bitmap image