Description of arrow
Home > biomechZoo > Toolbox > Support Functions > arrow.m
arrow
PURPOSE
trn ... origin of vector
SYNOPSIS
function [x,y,z] = arrow(trn,vec,res,mmg)
DESCRIPTION
 trn  ... origin of vector
 vec  ... head of vector
 res  ... thickness of vector
CROSS-REFERENCE INFORMATION
This function calls:
mtransform
surface2patch [vr,fc] = SURFACE2PATCH(x,y,z) converts surface orientation data to patch
vecrotate vout = VECROTATE(vin,ang,ax) rotates a vector any number of degrees about any axis
This function is called by:
costume
directorold updated by Phil Dixon Oct 2009
directorold2 updated by Phil Dixon Oct 2009
specialobject Updated by Philippe C. Dixon March 30th 2016
vectoraxes