Description of bargraphfxn
Home > biomechZoo > Toolbox > Support Functions > bargraphfxn.m
bargraphfxn
PURPOSE
SYNOPSIS
function varargout = bargraphfxn(action,varargin)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
actor
bargraphfxn
ctransform vout = CTRANSFORM(c1,c2,vec) will transform a vector from c1 to c2 (T2/1)
currentobject
currentunits
extension varargout = extension(f,ext) returns file extension. File extension can be changed if
grips edited by Phil Dixon Dec 2010
gunit
makeunit MAKEUNIT makes all vectors unit vectors
vecrotate vout = VECROTATE(vin,ang,ax) rotates a vector any number of degrees about any axis
This function is called by:
bargraphfxn
directorold updated by Phil Dixon Oct 2009
directorold2 updated by Phil Dixon Oct 2009
keypress