Description of batchdisp
Home > biomechZoo > Toolbox > Support Functions > batchdisp.m
batchdisp
PURPOSE
BATCHDISP(fl,type) produces a shortened display of file path
SYNOPSIS
function batchdisp(fl,type)
DESCRIPTION
 BATCHDISP(fl,type) produces a shortened display of file path
 ARGUMENTS
 fl    ... name of file being processed
 type  ... message specifyer. Default 'processing'
 Created June 2013 by Philippe C. Dixon
 Updated January 9th 2014 by Philippe C. Dixon
 - simplification of algorithm
 Updated Sept 23rd 2014 by Philippe C. Dixon
 - fixed bug when length(indx)==4
 Updated Aug 2017 by Philippe C. Dixon
 - Support for ensembler: if original caller function is ensembler, then
   disp will be pushed to ensembler message window
CROSS-REFERENCE INFORMATION
This function calls:
isin r = isin(str,a) verifies is substring 'substr' is in string or cell array of
This function is called by:
build_interjoint_test_data script to generate mat file data for testing inter-joint coordination
costume2prop costume2prop(fld) converts costume objects to props
delfile DELFILE(fl) deletes a single file or group of files
getmaxval getmaxval automatically checks all axes for maxdifference between conditons for later graphing