Description of bmech_continuous_stats_ensembler4
Home > biomechZoo > Toolbox > Support Functions > bmech_continuous_stats_ensembler4.m
bmech_continuous_stats_ensembler4
PURPOSE
bmech_continuous_stats_ensembler4 computes continuous stats based on Bootstrap confidence intervals
SYNOPSIS
function [compcons,maxval] = bmech_continuous_stats_ensembler4(fld,ch,r,alpha,ax,nboots,maxval,check,cohen)
DESCRIPTION
 bmech_continuous_stats_ensembler4 computes continuous stats based on Bootstrap confidence intervals
 ARGUMENTS
 fld          ...   directory where data resides
 ch           ...   channel of zoo file to investigate (string)
 alpha        ...   significance level (default 0.05)
 ax           ...   axis handle
 check        ...   check the summary statistics
 cohen        ...   use cohen's d insted of mean difference (boolean)
 RETURNS
 compconsstk  ...   used for ensembler. cons gives order of colorbars
 maxval       ...   maxval of all differences for color bar legend
 NOTE: Creating patch fails in MAC. No solution provided
 Created May 2012 by Philippe C. Dixon
 Updated June 2012
 - fixed small error with color reporting
 - better visualisation of color bars
 Updated August 2012
 -optimized for use in ensembler
 Updated November 2012
 - function can handle empty emsembler channels
 - small changes can be expressed over numerous colors
 updated Jan 12th 2013
 - complies with zoosystem v1.1
 updated Jan 19th 2013
 - maxval and mult are set here as default
 updated Feb 28th 2013
 - mult dependent on maxval
 updated July 27th 2013
 - function restructured for speed and clarity
 - mult and maxval computed automatically by function
 - function can handle unequal samples sizes
 Updatec October 23rd 2013
 - conditions can handle the '+' identifier in ensembler
CROSS-REFERENCE INFORMATION
This function calls:
computecolorbars made as stand alone function July 29th 2013
engine fl = ENGINE(varargin) is a file searching algorithm
isin r = isin(str,a) verifies is substring 'substr' is in string or cell array of
This function is called by: