Description of build_interjoint_test_data
Home > biomechZoo > Toolbox > Support Functions > build_interjoint_test_data.m
build_interjoint_test_data
PURPOSE
script to generate mat file data for testing inter-joint coordination
SYNOPSIS
This is a script file.
DESCRIPTION
 script to generate mat file data for testing inter-joint coordination
CROSS-REFERENCE INFORMATION
This function calls:
batchdisp BATCHDISP(fl,type) produces a shortened display of file path
engine fl = ENGINE(varargin) is a file searching algorithm
findfield [r,chn] = FINDFIELD(st,evt) searches through all subbranches in a structured array
uigetfolder UIGETFOLDER(title, initial_path) Standard Windows browse for folder dialog box.
vline function h=vline(x, linetype, label)
zload data = ZLOAD(fl) loads zoo files for quicker typing in batch processing
This function is called by: