Description of c3d2com
Home > biomechZoo > Toolbox > Support Functions > c3d2com.m
c3d2com
PURPOSE
data = c3d2com(c3d_data)
SYNOPSIS
function data = c3d2com(c3d)
DESCRIPTION
data = c3d2com(c3d_data)
This function will output segment information from a c3d file created by
vicon (using the plugin gait model).
Units are in CENTIMETERS
Caution.  all segments above and including the pelvis do not have the
proper center of mass
Created by JJ Loh  2007/06/21
Departement of Kinesiology
McGill University, Montreal, Quebec Canada
CROSS-REFERENCE INFORMATION
This function calls:
ctransform vout = CTRANSFORM(c1,c2,vec) will transform a vector from c1 to c2 (T2/1)
getchannelc3d r = getchannelc3d(c3ddata,label)
gunit
This function is called by: