Description of computecolorbars
Home > biomechZoo > Toolbox > Support Functions > computecolorbars.m
computecolorbars
PURPOSE
made as stand alone function July 29th 2013
SYNOPSIS
function [mdiffdatastk,maxvalstk,mult,cons,SigDiffIndxStk,frames,compconsstk,chat_con,maxvalcohenstk,cohendstk] = computecolorbars(r,cons,ch,fl,nboots,alpha,check,mode,cohen)
DESCRIPTION
 made as stand alone function July 29th 2013
 Updated November 18th 2013
 - function can handle any number of comparisons
 - stratified bootstrap is used unless number of lines are equal and
   condition names start with the same 2 letters.
CROSS-REFERENCE INFORMATION
This function calls:
getFramesContinuous
isin r = isin(str,a) verifies is substring 'substr' is in string or cell array of
This function is called by:
bmech_continuous_stats_ensembler4 bmech_continuous_stats_ensembler4 computes continuous stats based on Bootstrap confidence intervals
getmaxval getmaxval automatically checks all axes for maxdifference between conditons for later graphing