Description of costume2prop
Home > biomechZoo > Toolbox > Support Functions > costume2prop.m
costume2prop
PURPOSE
costume2prop(fld) converts costume objects to props
SYNOPSIS
function costume2prop(fld)
DESCRIPTION
 costume2prop(fld) converts costume objects to props
 ARGUMENTS
  fld ...  path to folder
CROSS-REFERENCE INFORMATION
This function calls:
batchdisp BATCHDISP(fl,type) produces a shortened display of file path
engine fl = ENGINE(varargin) is a file searching algorithm
extension varargout = extension(f,ext) returns file extension. File extension can be changed if
uigetfolder UIGETFOLDER(title, initial_path) Standard Windows browse for folder dialog box.
This function is called by: