Description of costume
Home > biomechZoo > Toolbox > Support Functions > costume.m
costume
PURPOSE
SYNOPSIS
function varargout = costume(action,varargin)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
actor
arrow trn ... origin of vector
cameraman
cleanpatch
closest this function finds the closest in mt to pt
colordobj
costume
ctransform vout = CTRANSFORM(c1,c2,vec) will transform a vector from c1 to c2 (T2/1)
currentobject
currentperson Updated Sept 2016
currentunits
directory
displace DISPLACE moves a matrix m to vector vec
extension varargout = extension(f,ext) returns file extension. File extension can be changed if
findpart
gunit
makecolumn MAKECOLUMN forces row vector to be a column vector
makerow MAKEROW forces a column vector to be a row vector
makeunit MAKEUNIT makes all vectors unit vectors
mtransform
point2line this function returns the row index of the matrix of points (pt) closest
rotatefaces
sculpttool
uigetfolder UIGETFOLDER(title, initial_path) Standard Windows browse for folder dialog box.
vecrotate vout = VECROTATE(vin,ang,ax) rotates a vector any number of degrees about any axis
This function is called by:
actor
costume
directorold updated by Phil Dixon Oct 2009
directorold2 updated by Phil Dixon Oct 2009
dkeypress
openall standalone function used by director
sculpttool