Description of createmarker
Home > biomechZoo > Toolbox > Support Functions > createmarker.m
createmarker
PURPOSE
ARGUMENTS
SYNOPSIS
function r = createmarker(nm,sz,dis,clr)
DESCRIPTION
 ARGUMENTS
  nm   ... name of marker
  sz   ... size of marker
  dis  ... n x 3 vector. Position of marker through time
  clr  ... the color of the new marker
CROSS-REFERENCE INFORMATION
This function calls:
displace DISPLACE moves a matrix m to vector vec
surface2patch [vr,fc] = SURFACE2PATCH(x,y,z) converts surface orientation data to patch
This function is called by:
directorold2 updated by Phil Dixon Oct 2009
marker varargout = marker(action,varargin) performs various actions for director
propscopy
zmarker