Description of currentperson
Home > biomechZoo > Toolbox > Support Functions > currentperson.m
currentperson
PURPOSE
Updated Sept 2016
SYNOPSIS
function r = currentperson
DESCRIPTION
 Updated Sept 2016
 - r returns as empty if hnd is empty
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
actor
costume
directorold updated by Phil Dixon Oct 2009
directorold2 updated by Phil Dixon Oct 2009
dkeypress
keypress
marker varargout = marker(action,varargin) performs various actions for director
propscopy
zmarker