Description of directorold
Home > biomechZoo > Toolbox > Support Functions > directorold.m
directorold
PURPOSE
updated by Phil Dixon Oct 2009
SYNOPSIS
function varargout = director(action,varargin)
DESCRIPTION
 updated by Phil Dixon Oct 2009
 -list of channels contains all changes (edited file marker.m line 114)
 - you can reload marker data using "reload marker"
 updated by Phil Dixon March 2010
 - you can load bones by clicking 'load bones' instead of using quick open
 - quick open has been removed from GUI
 - you can select to load a 'lower-limb' or 'full' plugin gait model
 updated by Phil Dixon December 2010
 - you can now plot any channel you want as long as it is a n x 1 channel
CROSS-REFERENCE INFORMATION
This function calls:
accessoryfxn
actor
arrow trn ... origin of vector
bargraphfxn
cameraman
colorpallete
controls
costume
currentobject
currentperson Updated Sept 2016
currentunits
displace DISPLACE moves a matrix m to vector vec
engine fl = ENGINE(varargin) is a file searching algorithm
extension varargout = extension(f,ext) returns file extension. File extension can be changed if
findpart
grips edited by Phil Dixon Dec 2010
gunit
isgravity
lightman
marker varargout = marker(action,varargin) performs various actions for director
openall standalone function used by director
partitionfile updated Jan 2013
pathname this m-file returns only the path to which the file belongs
sculpttool
specialobject Updated by Philippe C. Dixon March 30th 2016
uigetfolder UIGETFOLDER(title, initial_path) Standard Windows browse for folder dialog box.
This function is called by: