Description of displace
Home > biomechZoo > Toolbox > Support Functions > displace.m
displace
PURPOSE
DISPLACE moves a matrix m to vector vec
SYNOPSIS
function r = displace(m,vec)
DESCRIPTION
 DISPLACE moves a matrix m to vector vec
 R = DISPLACE(m,vec)
 ARGUMENTS
   m       ...  matrix to be displaced
   vec     ...  displacement vector
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
costume
createmarker ARGUMENTS
directorold updated by Phil Dixon Oct 2009
directorold2 updated by Phil Dixon Oct 2009
drawboneorientation
fan
fitobject this function will displace and rotate objvr to fit the fitvr
forceplate
grips edited by Phil Dixon Dec 2010
marker varargout = marker(action,varargin) performs various actions for director
move_rotateobject
propscopy
zmarker