Description of engine_old
Home > biomechZoo > Toolbox > Support Functions > engine_old.m
engine_old
PURPOSE
fl = ENGINE_OLD(varargin) is a file searching algorithm
SYNOPSIS
function fl = engine_old(varargin)
DESCRIPTION
 fl = ENGINE_OLD(varargin) is a file searching algorithm
 inputs are in pairs where the first element is the property name and the second is a property value
 The 'path' property is required.  All other properties are optional. All arguments must be strings.
 ARGUMENTS
  'pth, 'path' or 'fld'  ...  folder path to begin the search as string
  'extension' or 'ext'   ...  type of file to search as string. ex. '.c3d' or 'csv' ('.' not necessary)
  'search file'          ...  return only files containing specific string ex. '_g_'
  'search path'          ...  search for a particular string in the path name ex 'hello' in data/hello
  'folder'               ...  search only in folders of a specific name located downstream from the path (string)
 RETURNS
  fl                     ...  list of files as cell array of strings
 e.g. #1 Return all files in the root folder C:/Users/Public which contain the
 string 'imba':
 fl = engine('path','C:/Users/Public','search file','imba')
 e.g. #2 Return all files in the root folder C:/Users/Public which are
 located in the subfolder Sample Music:
 fld = 'C:/Users/Public';
 fl = engine('path',fld,'search path','Sample Music')
CROSS-REFERENCE INFORMATION
This function calls:
concatfile Updated by Phil Dixon Oct 2011
directory
iseven r = ISEVEN(x) determines if numeric data is even.
isin r = isin(str,a) verifies is substring 'substr' is in string or cell array of
This function is called by: