Description of euler2unit
Home > biomechZoo > Toolbox > Support Functions > euler2unit.m
euler2unit
PURPOSE
SYNOPSIS
function r = euler2unit(eu);
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
gunit
makeunit MAKEUNIT makes all vectors unit vectors
This function is called by:
accessoryfxn
actor
specialobject Updated by Philippe C. Dixon March 30th 2016