Description of extension
Home > biomechZoo > Toolbox > Support Functions > extension.m
extension
PURPOSE
varargout = extension(f,ext) returns file extension. File extension can be changed if
SYNOPSIS
function varargout = extension(f,ext)
DESCRIPTION
 varargout = extension(f,ext) returns file extension. File extension can be changed if
 second argument is provided
 updated by Philippe C. Dixon August 2013
 - changed to strfind from findstr at line 6
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
accessoryfxn
actor
bargraphfxn
cameraman
costume
costume2prop costume2prop(fld) converts costume objects to props
directorold updated by Phil Dixon Oct 2009
directorold2 updated by Phil Dixon Oct 2009
getextensions ext = getextensions(fl) returns file types from list of files
grab GRAB is the easy way to open .zoo and .c3d files. Simply type 'grab' and select
grips edited by Phil Dixon Dec 2010
marker varargout = marker(action,varargin) performs various actions for director
openall standalone function used by director
propscopy
sculpttool
specialobject Updated by Philippe C. Dixon March 30th 2016
stretch
tempprint
uigetstruct
zload data = ZLOAD(fl) loads zoo files for quicker typing in batch processing