Description of findfield
Home > biomechZoo > Toolbox > Support Functions > findfield.m
findfield
PURPOSE
[r,chn] = FINDFIELD(st,evt) searches through all subbranches in a structured array
SYNOPSIS
function [r,chn] = findfield(data,evt)
DESCRIPTION
 [r,chn] = FINDFIELD(st,evt) searches through all subbranches in a structured array
 ARGUMENTS
  data        ...  structured array
  evt       ...  name of event in structured array as string
 RETURNS
  r         ...  value of subbranch evt
  ch        ...   name of branch containing evt
CROSS-REFERENCE INFORMATION
This function calls:
findfield [r,chn] = FINDFIELD(st,evt) searches through all subbranches in a structured array
This function is called by:
actor
build_interjoint_test_data script to generate mat file data for testing inter-joint coordination
findfield [r,chn] = FINDFIELD(st,evt) searches through all subbranches in a structured array
getanthro ANTHRO = GETANTHRO(DATA) extracts anthropometric data from zoo file. If