Description of g
Home > biomechZoo > Toolbox > Support Functions > g.m
g
PURPOSE
r=G(city) returns value of acceleration in different cities. You can get really nerdy and
SYNOPSIS
function r=g(city)
DESCRIPTION
 r=G(city) returns value of acceleration in different cities. You can get really nerdy and
 use a city input if you like
 ARGUMENTS
  city  ...  optional input to specificy gravitational acceleration based
             on location. Default standard 9.807
 RETURNS
  r     ...  gravitational acceleration constant
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
grips edited by Phil Dixon Dec 2010
hline function h=hline(y, linetype, label)
readc3d DATA = READC3D(FNAME) will read a .c3d file and output the data in a structured array
velocity data = VELOCITY_DATA(data,ch,method) computes velocity of a motion capture
velocity_data data = VELOCITY_DATA(data,ch,method) computes velocity of a motion capture
vline function h=vline(x, linetype, label)