Description of getanthro
Home > biomechZoo > Toolbox > Support Functions > getanthro.m
getanthro
PURPOSE
ANTHRO = GETANTHRO(DATA) extracts anthropometric data from zoo file. If
SYNOPSIS
function [r,data] = getanthro(data,field)
DESCRIPTION
 ANTHRO = GETANTHRO(DATA) extracts anthropometric data from zoo file. If
 data are not available an attempt to compute information is made. This
 function is useful to query without error unusual anthro field names.
 ARGUMENTS
  data     ...   zoo data structure
 RETURNS
  anthro   ...   structured array containing all available zoo fields
CROSS-REFERENCE INFORMATION
This function calls:
findfield [r,chn] = FINDFIELD(st,evt) searches through all subbranches in a structured array
getanthro ANTHRO = GETANTHRO(DATA) extracts anthropometric data from zoo file. If
magnitude m = MAGNITUDE(r) takes the magnitude of a signal
This function is called by:
getanthro ANTHRO = GETANTHRO(DATA) extracts anthropometric data from zoo file. If