Description of getchannelc3d
Home > biomechZoo > Toolbox > Support Functions > getchannelc3d.m
getchannelc3d
PURPOSE
r = getchannelc3d(c3ddata,label)
SYNOPSIS
function r = getchannelc3d(c3ddata,label,varargin)
DESCRIPTION
r = getchannelc3d(c3ddata,label)
Will get the data for an analog channel
label = the channel label as a string eg 'FX1'
The channel name is case sensitive and it includes any trailing blanks
r = getchannelc3d(c3ddata,label,dim)
will get the data for a Video channel
dim = 'x','y','z',or 'all';
Created by JJ Loh  2006/09/20
Departement of Kinesiology
McGill University, Montreal, Quebec Canada
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
c3d2com data = c3d2com(c3d_data)
plugingait
propscopy
zmarker