Description of getFPGlobalOrigin
Home > biomechZoo > Toolbox > Support Functions > getFPGlobalOrigin.m
getFPGlobalOrigin
PURPOSE
GetFPGlobalOrigin extracts the coordinates of the centre of each force
SYNOPSIS
function [globalOr, orient] = getFPGlobalOrigin(data)
DESCRIPTION
 GetFPGlobalOrigin extracts the coordinates of the centre of each force
 plate in GCS
 Notes
 - corners start in top right corner and go counter clockwise
 - For oxford gait lab, the output of this function should be
 Or1 = [0.232    0.254    0];
 Or2 = [0.232    -0.324    0];
 Or3 = [0.233    0.916    0];
 - values are in mm
 Updated by Philippe C. Dixon July 2017
 - Adds height of force plates for situations where force plates are not
   on the ground. E.g. stair case study
CROSS-REFERENCE INFORMATION
This function calls:
get_nforceplates find number of force plates used
intersection computes the intersetion of a_b and u_v
makerow MAKEROW forces a column vector to be a row vector
makeunit MAKEUNIT makes all vectors unit vectors
This function is called by:
kistlerGRF_data data = KISTLERGRF_data(data) computes GRF data for Kistler force