Description of getmaxval
Home > biomechZoo > Toolbox > Support Functions > getmaxval.m
getmaxval
PURPOSE
getmaxval automatically checks all axes for maxdifference between conditons for later graphing
SYNOPSIS
function [maxval,temp,mult] = getmaxval(fld,ch,alpha,ax,nboots,check,cohen)
DESCRIPTION
 getmaxval automatically checks all axes for maxdifference between conditons for later graphing
 ARGUMENTS
 fld          ...   directory where data resides
 ch           ...   channel of zoo file to investigate (string)
 ax           ...   axis handle
 RETURNS
 maxval       ...   maxval of all differences for color bar legend
 Created July 29th 2013 by Philippe C. Dixon
 Updatec October 23rd 2013
 - conditions can handle the '+' identifier in ensembler
CROSS-REFERENCE INFORMATION
This function calls:
batchdisp BATCHDISP(fl,type) produces a shortened display of file path
computecolorbars made as stand alone function July 29th 2013
engine fl = ENGINE(varargin) is a file searching algorithm
isin r = isin(str,a) verifies is substring 'substr' is in string or cell array of
zload data = ZLOAD(fl) loads zoo files for quicker typing in batch processing
This function is called by: