Description of grips
Home > biomechZoo > Toolbox > Support Functions > grips.m
grips
PURPOSE
edited by Phil Dixon Dec 2010
SYNOPSIS
function varargout = grips(action,varargin)
DESCRIPTION
 edited by Phil Dixon Dec 2010
 - handle to axes output during 'data graph' case
CROSS-REFERENCE INFORMATION
This function calls:
actor
associatedlg Main dialog box interface used by ensembler
cameraman
ctransform vout = CTRANSFORM(c1,c2,vec) will transform a vector from c1 to c2 (T2/1)
currentobject
currentunits
displace DISPLACE moves a matrix m to vector vec
extension varargout = extension(f,ext) returns file extension. File extension can be changed if
fan
findpart
g r=G(city) returns value of acceleration in different cities. You can get really nerdy and
grips edited by Phil Dixon Dec 2010
gunit
makeunit MAKEUNIT makes all vectors unit vectors
mergepatch
mtransform
uigetstruct
This function is called by:
actor
bargraphfxn
directorold updated by Phil Dixon Oct 2009
directorold2 updated by Phil Dixon Oct 2009
dkeypress
grips edited by Phil Dixon Dec 2010
openall standalone function used by director
specialobject Updated by Philippe C. Dixon March 30th 2016
zmarker