Description of gunit
Home > biomechZoo > Toolbox > Support Functions > gunit.m
gunit
PURPOSE
SYNOPSIS
function r = gunit;
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
accessoryfxn
bargraphfxn
c3d2com data = c3d2com(c3d_data)
cameracontrol
cameraman
chop pln consists of 3 points that make the plane
cine_groot_suntay
costume
directorold updated by Phil Dixon Oct 2009
directorold2 updated by Phil Dixon Oct 2009
drawboneorientation
euler2unit
fan
fitobject this function will displace and rotate objvr to fit the fitvr
forceplate
getjointcenters Lhipvec = [0.001047173543632 0.008637260481034 0.987698733491366];
grips edited by Phil Dixon Dec 2010
lightman
move_rotateobject
movepoint
propscopy
rotatefaces
specialobject Updated by Philippe C. Dixon March 30th 2016