Description of isin
Home > biomechZoo > Toolbox > Support Functions > isin.m
isin
PURPOSE
r = isin(str,a) verifies is substring 'substr' is in string or cell array of
SYNOPSIS
function r= isin(str,substr)
DESCRIPTION
 r = isin(str,a) verifies is substring 'substr' is in string or cell array of
 strings 'str'
 ARGUMENTS
 str ...  string or cell array of strings
 substr   ...  substring
 RETURN
 r   ...  logical 0 or 1
 Updated Oct 2013
 - imporved help function
 Updated February 2014
 - can accept cell array of srings for multiple comparisons
 Updated Oct 2020
 - added deprecation warning.
 Updated Nov 2020
 - removed depreciation to maintain support for older versions
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
batchdisp BATCHDISP(fl,type) produces a shortened display of file path
bmech_continuous_stats_ensembler4 bmech_continuous_stats_ensembler4 computes continuous stats based on Bootstrap confidence intervals
computecolorbars made as stand alone function July 29th 2013
computecolorbars_old made as stanalone function July 29th 2013
directorold2 updated by Phil Dixon Oct 2009
engine_old fl = ENGINE_OLD(varargin) is a file searching algorithm
getmaxval getmaxval automatically checks all axes for maxdifference between conditons for later graphing
marker varargout = marker(action,varargin) performs various actions for director
readcsvVicon r = READCSVVICON(fl)reads csv files generated by the Vicon Nexus
velocity data = VELOCITY_DATA(data,ch,method) computes velocity of a motion capture
velocity_data data = VELOCITY_DATA(data,ch,method) computes velocity of a motion capture