Description of magnitude
Home > biomechZoo > Toolbox > Support Functions > magnitude.m
magnitude
PURPOSE
m = MAGNITUDE(r) takes the magnitude of a signal
SYNOPSIS
function m=magnitude(r)
DESCRIPTION
 m = MAGNITUDE(r) takes the magnitude of a signal
 ARGUMENTS
  r       ....     n x 3 signal
 RETURNS
  m       ....    magnitude of the signal
CROSS-REFERENCE INFORMATION
This function calls:
makecolumn MAKECOLUMN forces row vector to be a column vector
This function is called by:
fitobject this function will displace and rotate objvr to fit the fitvr
forceplate
getanthro ANTHRO = GETANTHRO(DATA) extracts anthropometric data from zoo file. If
makeunit MAKEUNIT makes all vectors unit vectors
velocity data = VELOCITY_DATA(data,ch,method) computes velocity of a motion capture
velocity_data data = VELOCITY_DATA(data,ch,method) computes velocity of a motion capture