Description of makeunit
Home > biomechZoo > Toolbox > Support Functions > makeunit.m
makeunit
PURPOSE
MAKEUNIT makes all vectors unit vectors
SYNOPSIS
function r = makeunit(unt)
DESCRIPTION
   MAKEUNIT  makes all vectors unit vectors
   unt ... N by 3 matrix of vectors.
           rows are the number of vectors
           columns are XYZ
 Created by JJ Loh ??
 updated November 2011 by Phil Dixon
 - can normalize nx2 vectors
 updated May 2022 by Phil Dixon
 - rely on magnitude function
CROSS-REFERENCE INFORMATION
This function calls:
magnitude m = MAGNITUDE(r) takes the magnitude of a signal
This function is called by:
bargraphfxn
cameracontrol
cameraman
chop pln consists of 3 points that make the plane
cine_groot_suntay
costume
drawboneorientation
euler2unit
fan
fitobject this function will displace and rotate objvr to fit the fitvr
forceplate
getFPGlobalOrigin GetFPGlobalOrigin extracts the coordinates of the centre of each force
grips edited by Phil Dixon Dec 2010
lightman
move_rotateobject
movepoint
point2line this function returns the row index of the matrix of points (pt) closest
pointplane
propscopy
rotatefaces
specialobject Updated by Philippe C. Dixon March 30th 2016