Description of makecolumn
Home > biomechZoo > Toolbox > Support Functions > makecolumn.m
makecolumn
PURPOSE
MAKECOLUMN forces row vector to be a column vector
SYNOPSIS
function r = makecolumn(s)
DESCRIPTION
   MAKECOLUMN forces row vector to be a column vector
 Updated March 3rd 2015 by Philippe C. Dixon
 - works with cell arrays
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
bardlg
costume
magnitude m = MAGNITUDE(r) takes the magnitude of a signal
mylistdlg
propscopy
readc3d DATA = READC3D(FNAME) will read a .c3d file and output the data in a structured array
stdpatch This function creates std patches for graphing purposes
vecrotate vout = VECROTATE(vin,ang,ax) rotates a vector any number of degrees about any axis