Description of marker
Home > biomechZoo > Toolbox > Support Functions > marker.m
marker
PURPOSE
varargout = marker(action,varargin) performs various actions for director
SYNOPSIS
function varargout = marker(action,varargin)
DESCRIPTION
 varargout = marker(action,varargin) performs various actions for director
 Updated by JJ Loh and Philippe C. Dixon June 2015
 - new case added to load the skate props
 Updated by Philippe C. Dixon Jan 2016
 - Bug fixes for backwards comp
 Updated by Philippe C. Dixon June 2017
 - clean up pop up window for marker selection
 Updated by Philippe C. Dixon July 2017
 - added creation of PiG bones, if available
 Updated by Philippe C. Dixon August 2017
 - Exploded PiG data are automatically merged in order to build bones, if available
 Updated by Philippe C. Dixon January 2018
 - Improved search for markers to display
 - Attempts to merge exploded marker data to display markers in director
CROSS-REFERENCE INFORMATION
This function calls:
cameraman
createmarker ARGUMENTS
currentperson Updated Sept 2016
displace DISPLACE moves a matrix m to vector vec
engine fl = ENGINE(varargin) is a file searching algorithm
explode EXPLODE Splits string into pieces.
extension varargout = extension(f,ext) returns file extension. File extension can be changed if
isin r = isin(str,a) verifies is substring 'substr' is in string or cell array of
newcolor
pathname this m-file returns only the path to which the file belongs
surface2patch [vr,fc] = SURFACE2PATCH(x,y,z) converts surface orientation data to patch
zload data = ZLOAD(fl) loads zoo files for quicker typing in batch processing
This function is called by:
directorold updated by Phil Dixon Oct 2009
directorold2 updated by Phil Dixon Oct 2009
openall standalone function used by director
propscopy