Description of openall
Home > biomechZoo > Toolbox > Support Functions > openall.m
openall
PURPOSE
standalone function used by director
SYNOPSIS
function openall(pth)
DESCRIPTION
 standalone function used by director
CROSS-REFERENCE INFORMATION
This function calls:
actor
cameraman
costume
engine fl = ENGINE(varargin) is a file searching algorithm
extension varargout = extension(f,ext) returns file extension. File extension can be changed if
grips edited by Phil Dixon Dec 2010
lightman
marker varargout = marker(action,varargin) performs various actions for director
partitionfile updated Jan 2013
This function is called by:
directorold updated by Phil Dixon Oct 2009
directorold2 updated by Phil Dixon Oct 2009