Description of pathname
Home > biomechZoo > Toolbox > Support Functions > pathname.m
pathname
PURPOSE
this m-file returns only the path to which the file belongs
SYNOPSIS
function path = pathname(fl)
DESCRIPTION
 this m-file returns only the path to which the file belongs
 ARGUMENTS
     fl      ...   complete file name as string.
 RETURNS
     path   ...   path of file
 Created Feb 2010
 © Part of the Biomechanics Toolbox, Copyright ©2008-2010
 Phil Dixon, Montreal, Qc, CANADA
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
directorold updated by Phil Dixon Oct 2009
directorold2 updated by Phil Dixon Oct 2009
marker varargout = marker(action,varargin) performs various actions for director
xlswrite1 In order to use it, one must place the following code within the program, as given by Matt Swartz. It opens/closes the activex server, load an add-in if any (by default when Excel opens as a COM server it does NOT load add-ins), and checks to see if the file already exists:
zooinfo The biomechZoo biomechanics Toolbox Copyright (c) 2006-2020 (Main contributors)