Description of plugingait
Home > biomechZoo > Toolbox > Support Functions > plugingait.m
plugingait
PURPOSE
SYNOPSIS
function ob = plugingait(bones,c3d)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
concatfile Updated by Phil Dixon Oct 2011
getchannelc3d r = getchannelc3d(c3ddata,label)
readc3d DATA = READC3D(FNAME) will read a .c3d file and output the data in a structured array
readobj
uigetfolder UIGETFOLDER(title, initial_path) Standard Windows browse for folder dialog box.
This function is called by:
propscopy