Description of point2line
Home > biomechZoo > Toolbox > Support Functions > point2line.m
point2line
PURPOSE
this function returns the row index of the matrix of points (pt) closest
SYNOPSIS
function index = point2line(pt,ln)
DESCRIPTION
this function returns the row index of the matrix of points (pt) closest
to the tail and to the line
line defined by ln (tail to head)
CROSS-REFERENCE INFORMATION
This function calls:
ctransform vout = CTRANSFORM(c1,c2,vec) will transform a vector from c1 to c2 (T2/1)
makeunit MAKEUNIT makes all vectors unit vectors
This function is called by:
actor
costume