Description of propscopy
Home > biomechZoo > Toolbox > Support Functions > propscopy.m
propscopy
PURPOSE
SYNOPSIS
function varargout = props(action,varargin)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
angle Calculates the smallest angle between two vectors, m1 and m2.
associatedlg Main dialog box interface used by ensembler
cameraman
colorpallete
createmarker ARGUMENTS
ctransform vout = CTRANSFORM(c1,c2,vec) will transform a vector from c1 to c2 (T2/1)
currentobject
currentperson Updated Sept 2016
displace DISPLACE moves a matrix m to vector vec
engine fl = ENGINE(varargin) is a file searching algorithm
extension varargout = extension(f,ext) returns file extension. File extension can be changed if
fitobject this function will displace and rotate objvr to fit the fitvr
forceplate
getchannelc3d r = getchannelc3d(c3ddata,label)
gunit
listchannelc3d
makecolumn MAKECOLUMN forces row vector to be a column vector
makerow MAKEROW forces a column vector to be a row vector
makeunit MAKEUNIT makes all vectors unit vectors
marker varargout = marker(action,varargin) performs various actions for director
partitionfile updated Jan 2013
plugingait
readc3d DATA = READC3D(FNAME) will read a .c3d file and output the data in a structured array
surface2patch [vr,fc] = SURFACE2PATCH(x,y,z) converts surface orientation data to patch
uigetfolder UIGETFOLDER(title, initial_path) Standard Windows browse for folder dialog box.
vecrotate vout = VECROTATE(vin,ang,ax) rotates a vector any number of degrees about any axis
This function is called by: