Description of readc3d
Home > biomechZoo > Toolbox > Support Functions > readc3d.m
readc3d
PURPOSE
DATA = READC3D(FNAME) will read a .c3d file and output the data in a structured array
SYNOPSIS
function data =readc3d(fname)
DESCRIPTION
 DATA = READC3D(FNAME) will read a .c3d file and output the data in a structured array
 ARGUMENTS
  fname     ... the c3d file and path (as a string) eg: 'c:\documents\myfile.c3d'
 RETURNS
  data      ...  structured array
 Notes
 - Machinetype variable may not be correct for intel or MIPS C3D files.
   This m-file needs to be tested with C3D files of these types.
   This m-file was tested and passed with DEC (VAX PDP-11) C3D files
 - Only character, integer, and real numbers have been tested.
   see http://www.c3d.org/HTML/default.htm for information
 - Residuals of 3D data are not handled
CROSS-REFERENCE INFORMATION
This function calls:
g r=G(city) returns value of acceleration in different cities. You can get really nerdy and
makecolumn MAKECOLUMN forces row vector to be a column vector
makevalidfield ch = makevalidfield(ch) fixes common invalid field names for structed
This function is called by:
grab GRAB is the easy way to open .zoo and .c3d files. Simply type 'grab' and select
plugingait
propscopy
zmarker