Description of readcsvVicon
Home > biomechZoo > Toolbox > Support Functions > readcsvVicon.m
readcsvVicon
PURPOSE
r = READCSVVICON(fl)reads csv files generated by the Vicon Nexus
SYNOPSIS
function r = readcsvVicon(fl)
DESCRIPTION
 r = READCSVVICON(fl)reads csv files generated by the Vicon Nexus
 ARGUMENTS
  fl    ...  Full file name and path of csv file (string)
 RETURNS
  r     ...  Structured array
 NOTES
 - Files should be exported using LEgacy "Export data to ASCII file" function
 - all outputs should be checked in "ASCII Dump options"
 - "Invalid co-ordinate value" should be left blank
 - Gait events identified in Nexus will appear under the event branch of the
   SACR channel if it exists, otherwise, they will appear in the the first channel
   in the video channel list
 Created by Philippe C. Dixon October 2012
 Updated by Philippe C. Dixon November 2013
 - event bug fixed
CROSS-REFERENCE INFORMATION
This function calls:
isin r = isin(str,a) verifies is substring 'substr' is in string or cell array of
makevalidfield ch = makevalidfield(ch) fixes common invalid field names for structed
readtext Usage: [data, result]= readtext(source, delimiter, comment, quotes, options)
This function is called by: