Description of rotatefaces
Home > biomechZoo > Toolbox > Support Functions > rotatefaces.m
rotatefaces
PURPOSE
SYNOPSIS
function nfc = rotatefaces(vr,fc,outside)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
angle Calculates the smallest angle between two vectors, m1 and m2.
ctransform vout = CTRANSFORM(c1,c2,vec) will transform a vector from c1 to c2 (T2/1)
gunit
makeunit MAKEUNIT makes all vectors unit vectors
This function is called by:
costume