Description of sculpttool
Home > biomechZoo > Toolbox > Support Functions > sculpttool.m
sculpttool
PURPOSE
SYNOPSIS
function varargout = sculpttool(action,varargin)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
cameraman
costume
ctransform vout = CTRANSFORM(c1,c2,vec) will transform a vector from c1 to c2 (T2/1)
currentobject
currentunits
extension varargout = extension(f,ext) returns file extension. File extension can be changed if
findclosevert this function returns the indices in vr1 and vr2 that are close to each other within the
findpart
keypress
pointplane
sculpttool
vecrotate vout = VECROTATE(vin,ang,ax) rotates a vector any number of degrees about any axis
This function is called by:
costume
directorold updated by Phil Dixon Oct 2009
directorold2 updated by Phil Dixon Oct 2009
dkeypress
sculpttool