Description of specialobject
Home > biomechZoo > Toolbox > Support Functions > specialobject.m
specialobject
PURPOSE
Updated by Philippe C. Dixon March 30th 2016
SYNOPSIS
function varargout = specialobject(action,varargin)
DESCRIPTION
 Updated by Philippe C. Dixon March 30th 2016
 - uses general function 'angle' for calculation of angle instead of
   embedded function
CROSS-REFERENCE INFORMATION
This function calls:
angle Calculates the smallest angle between two vectors, m1 and m2.
arrow trn ... origin of vector
bardlg
cameraman
closest this function finds the closest in mt to pt
ctransform vout = CTRANSFORM(c1,c2,vec) will transform a vector from c1 to c2 (T2/1)
currentobject
currentunits
euler2unit
extension varargout = extension(f,ext) returns file extension. File extension can be changed if
findpart
grips edited by Phil Dixon Dec 2010
gunit
keypress
makeunit MAKEUNIT makes all vectors unit vectors
searchstruct
unit2euler
vecrotate vout = VECROTATE(vin,ang,ax) rotates a vector any number of degrees about any axis
This function is called by:
actor
directorold updated by Phil Dixon Oct 2009
directorold2 updated by Phil Dixon Oct 2009
dkeypress
uicreatebars