Description of surface2patch
Home > biomechZoo > Toolbox > Support Functions > surface2patch.m
surface2patch
PURPOSE
[vr,fc] = SURFACE2PATCH(x,y,z) converts surface orientation data to patch
SYNOPSIS
function [vr,fc] = surface2patch(x,y,z)
DESCRIPTION
 [vr,fc] = SURFACE2PATCH(x,y,z) converts surface orientation data to patch
 vertices format
 ARGUMENTS
 x,y,z      ...  surface data
 RETURNS
 vr         ...  vertices for patch object
 fc         ...  faces for patch object
 Example
 [x,y,z] = cylinder(10,1);
 [vr,fc] = surface2patch(x,y,z);
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
arrow trn ... origin of vector
createmarker ARGUMENTS
marker varargout = marker(action,varargin) performs various actions for director
mysphere
propscopy