Description of uigetfolder
Home > biomechZoo > Toolbox > Support Functions > uigetfolder.m
uigetfolder
PURPOSE
UIGETFOLDER(title, initial_path) Standard Windows browse for folder dialog box.
SYNOPSIS
function folder = uigetfolder(title, initial_path)
DESCRIPTION
 UIGETFOLDER(title, initial_path)  Standard Windows browse for folder dialog box.
   folder = uigetfolder(title, initial_path)
   Output: folder       = selected folder (empty string if dialog cancelled)
   Inputs: title        = title string (OPTIONAL)
           initial_path = initial path (OPTIONAL, defaults to PWD)
   Examples:   folder = uigetfolder                          - default title and initial path
               folder = uigetfolder('Select results folder') - default initial path
               folder = uigetfolder([], 'C:\Program Files')  - default title
   See also UIGETFILE, UIPUTFILE
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
build_interjoint_test_data script to generate mat file data for testing inter-joint coordination
colorprops
costume
costume2prop costume2prop(fld) converts costume objects to props
directorold updated by Phil Dixon Oct 2009
exportfig filename = EXPORTFIG(fld,filename) exports ensembler figures for use in publications / LateX
plugingait
propscopy
setZooFld fld = SETZOOFLD(fld,mode,name) prepares folders for batch processing