Description of uigetstruct
Home > biomechZoo > Toolbox > Support Functions > uigetstruct.m
uigetstruct
PURPOSE
SYNOPSIS
function varargout = uigetstruct(varargin);
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
allfieldnames
extension varargout = extension(f,ext) returns file extension. File extension can be changed if
mylistdlg
searchstruct
This function is called by:
actor
grips edited by Phil Dixon Dec 2010