Description of vecrotate
Home > biomechZoo > Toolbox > Support Functions > vecrotate.m
vecrotate
PURPOSE
vout = VECROTATE(vin,ang,ax) rotates a vector any number of degrees about any axis
SYNOPSIS
function vout = vecrotate(vin,ang,ax)
DESCRIPTION
 vout = VECROTATE(vin,ang,ax) rotates a vector any number of degrees about any axis
 ARGUMENTS
  vin     ...    n x 3 matrix to rotate
  ang     ...    Angular rotation (in degrees)
  ax      ...    Axes to rotate about (string): 'x','y','z' or 'i','j','k'
 RETURN
  vout    ...    Rotated n x 3 matrix
 See also ctransform
CROSS-REFERENCE INFORMATION
This function calls:
deg2rad rad = DEG2RAD(deg) converts degrees to radians
makecolumn MAKECOLUMN forces row vector to be a column vector
This function is called by:
actor
arrow trn ... origin of vector
bargraphfxn
cameraman
costume
fan
forceplate
move_rotateobject
propscopy
sculpttool
specialobject Updated by Philippe C. Dixon March 30th 2016
vectoraxes