Description of zload
Home > biomechZoo > Toolbox > Support Functions > zload.m
zload
PURPOSE
data = ZLOAD(fl) loads zoo files for quicker typing in batch processing
SYNOPSIS
function data = zload(fl)
DESCRIPTION
 data = ZLOAD(fl) loads zoo files for quicker typing in batch processing
 ARGUMENTS
  fl    ... complete file path of file (string)
 RETURN
  data  ... zoo data (struct)
 See also zsave
CROSS-REFERENCE INFORMATION
This function calls:
extension varargout = extension(f,ext) returns file extension. File extension can be changed if
This function is called by:
bmech_zoo2table BMECH_ZOO2TABLE (fld,ch,subjects,conditions) extracts channel line data
build_interjoint_test_data script to generate mat file data for testing inter-joint coordination
directorold2 updated by Phil Dixon Oct 2009
getFramesContinuous
getmaxval getmaxval automatically checks all axes for maxdifference between conditons for later graphing
marker varargout = marker(action,varargin) performs various actions for director
structplot STRUCTPLOT plots any number of given channels in a structed array. If no