Description of zmarker
Home > biomechZoo > Toolbox > Support Functions > zmarker.m
zmarker
PURPOSE
SYNOPSIS
function varargout = zmarker(action,varargin)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
cameraman
createmarker ARGUMENTS
currentperson Updated Sept 2016
displace DISPLACE moves a matrix m to vector vec
getchannelc3d r = getchannelc3d(c3ddata,label)
grips edited by Phil Dixon Dec 2010
listchannelc3d
newcolor
plugingaitchannels
readc3d DATA = READC3D(FNAME) will read a .c3d file and output the data in a structured array
This function is called by: