Description of zooinfo
Home > biomechZoo > Toolbox > Support Functions > zooinfo.m
zooinfo
PURPOSE
The biomechZoo biomechanics Toolbox Copyright (c) 2006-2020 (Main contributors)
SYNOPSIS
function [version_num,version_date] = zooinfo(verbose)
DESCRIPTION
 The biomechZoo biomechanics Toolbox Copyright (c) 2006-2020 (Main contributors)
 Main contributor:
 Philippe C. Dixon, PhD
CROSS-REFERENCE INFORMATION
This function calls:
pathname this m-file returns only the path to which the file belongs
zooinfo The biomechZoo biomechanics Toolbox Copyright (c) 2006-2020 (Main contributors)
This function is called by:
setZoosystem zoosystem = SETZOOSYSTEM(fl) creates 'zoosystem' branch for data
zooinfo The biomechZoo biomechanics Toolbox Copyright (c) 2006-2020 (Main contributors)
zoosystem ZOOSYSTEM gives a quick summary of the functions included in the
zsave ZSAVE(fl,data,message) saves zoo files to disk with processing step information appended to the